/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tugas4;

import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Color;
import java.awt.Font;
import java.io.File;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.plaf.TabbedPaneUI;

/**
 *
 * @author Admin
 */
public class cekAngka extends javax.swing.JFrame {

      public static Random random = new Random();
      public static int angkaRandom = random.nextInt(101), nyawa = 100;
      public static String directory = "", warna = "";
      
      ArrayList<String> nama = new ArrayList<>();
      
//    ImageIcon icon = new ImageIcon("src/iniapotek/img/"+detail+".png");
//        jLabelDetailGambar.setIcon(icon);
    public cekAngka() {
        initComponents();
        try{
            File fontStyle = new File("src/tugas4/Poppins-Regular.ttf");
            Font font24 = Font.createFont(Font.TRUETYPE_FONT, fontStyle).deriveFont(20f);
            Font font18 = Font.createFont(Font.TRUETYPE_FONT, fontStyle).deriveFont(18f);
            jLabelTebak.setFont(font24);
            jLabelInputAngka.setFont(font18);
            jLabelAngkaAtas.setFont(font18);
            jLabelAngkaBawah.setFont(font18);
            jLabelAngkaAtas.setText("");
           jLabelAngkaBawah.setText("");
            
//            jPanelCard.setBackground( Color.white );
//            jLabel1.putClientProperty( FlatClientProperties.STYLE, "arc: 15" );

            
        }catch(Exception e){
            e.printStackTrace();
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabelTebak = new javax.swing.JLabel();
        jPanelCard = new javax.swing.JPanel();
        jLabelAngkaAtas = new javax.swing.JLabel();
        jLabelAngkaBawah = new javax.swing.JLabel();
        jLabelCard = new javax.swing.JLabel();
        jLabelInputAngka = new javax.swing.JLabel();
        jTextFieldInputAngka = new javax.swing.JTextField();
        jButtonTebak = new javax.swing.JButton();
        jButtonReset = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaOutput = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(706, 622));
        setMinimumSize(new java.awt.Dimension(706, 622));
        setPreferredSize(new java.awt.Dimension(706, 622));
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(622, 60));
        jPanel1.setPreferredSize(new java.awt.Dimension(622, 50));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 706, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel7.setBackground(new java.awt.Color(248, 246, 246));

        jLabelTebak.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelTebak.setText("Coba Tebak Angka Berapa Aku?");

        jPanelCard.setMaximumSize(new java.awt.Dimension(210, 266));
        jPanelCard.setMinimumSize(new java.awt.Dimension(210, 266));
        jPanelCard.setLayout(null);

        jLabelAngkaAtas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelAngkaAtas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAngkaAtas.setText("1");
        jPanelCard.add(jLabelAngkaAtas);
        jLabelAngkaAtas.setBounds(150, 10, 50, 25);

        jLabelAngkaBawah.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelAngkaBawah.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAngkaBawah.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAngkaBawah.setText("1");
        jPanelCard.add(jLabelAngkaBawah);
        jLabelAngkaBawah.setBounds(0, 230, 50, 25);

        jLabelCard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/backCard.jpg"))); // NOI18N
        jPanelCard.add(jLabelCard);
        jLabelCard.setBounds(0, 0, 210, 266);

        jLabelInputAngka.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelInputAngka.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelInputAngka.setText("Masukkan Angka");

        jButtonTebak.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonTebak.setText("Tebak ( 10 )");
        jButtonTebak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTebakActionPerformed(evt);
            }
        });

        jButtonReset.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonReset.setText("Reset");
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(jLabelTebak))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jButtonTebak, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jTextFieldInputAngka)
                            .addComponent(jPanelCard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelInputAngka, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE))))
                .addContainerGap(193, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabelTebak, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelCard, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelInputAngka, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldInputAngka, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonTebak, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(jButtonReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel7, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Card Game", jPanel3);

        jTextAreaOutput.setEditable(false);
        jTextAreaOutput.setColumns(20);
        jTextAreaOutput.setRows(5);
        jScrollPane1.setViewportView(jTextAreaOutput);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(117, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("History", jPanel4);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        getContentPane().add(jPanel2);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonTebakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTebakActionPerformed
        // TODO add your handling code here:
        int inputAngka = Integer.parseInt(jTextFieldInputAngka.getText());
        if (nyawa == 0){
            JOptionPane.showMessageDialog(this,"WARNING", "ERRORR BOSS", JOptionPane.WARNING_MESSAGE);
            jButtonTebak.setText("Tebak ( 10 )");
            nyawa = 100;
            jLabelCard.setIcon(new ImageIcon("src/img/backCard.jpg"));
            jButtonTebak.setText("Tebak ( 10 )");
            angkaRandom = random.nextInt(101);
           jTextFieldInputAngka.setText("");
           jLabelAngkaAtas.setText("");
           jLabelAngkaBawah.setText("");
        }
        else{
            if(inputAngka < angkaRandom){
            JOptionPane.showMessageDialog(this, "angka lebih kecil");
            nyawa-=10;
            jButtonTebak.setText("Tebak ( " + String.valueOf(nyawa/10)+ " )");
            jTextFieldInputAngka.setText("");
        }
        
         if(inputAngka > angkaRandom){
            JOptionPane.showMessageDialog(this, "angka lebih besar");
            nyawa-=10;
            jButtonTebak.setText("Tebak ( " + String.valueOf(nyawa/10)+ " )");
            jTextFieldInputAngka.setText("");
        }
          if(inputAngka == angkaRandom){
            ImageIcon icon = new ImageIcon(directory);
            jLabelCard.setIcon(icon);
            jLabelAngkaAtas.setText(String.valueOf(angkaRandom));
            jLabelAngkaAtas.setForeground(Color.decode(warna));
            jLabelAngkaBawah.setText(String.valueOf(angkaRandom));
            String inputNama = JOptionPane.showInputDialog(this, "masukkan nama anda : ");
            nama.add("| Nama : " + inputNama + "\n| Score : " + String.valueOf(nyawa)+"\n|=======================================\n");
            String nilaiOutput ="";
           for (String output : nama){
               nilaiOutput = nilaiOutput + output;
           } 
           
           jLabelCard.setIcon(new ImageIcon("src/img/backCard.jpg"));
           jLabelAngkaAtas.setText("");
           jLabelAngkaBawah.setText("");
           jButtonTebak.setText("Tebak ( 10 )");
           jTextAreaOutput.setText(nilaiOutput);
           jTextFieldInputAngka.setText("");
           angkaRandom = random.nextInt(101);
              System.out.println(angkaRandom);
           nyawa = 100;
        }
        }
        
    }//GEN-LAST:event_jButtonTebakActionPerformed

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
        // TODO add your handling code here:
        jLabelCard.setIcon(new ImageIcon("src/img/backCard.jpg"));
           jButtonTebak.setText("Tebak ( 10 )");
           jLabelAngkaAtas.setText("");
           jLabelAngkaBawah.setText("");
           jTextFieldInputAngka.setText("");
           angkaRandom = random.nextInt(101);
              System.out.println(angkaRandom);
           nyawa = 100;
    }//GEN-LAST:event_jButtonResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) { /* Set the Nimbus look and feel */ //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
                //</editor-fold>
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
            UIManager.put("jLabel.arc", 15);  
        } catch (Exception e) {
        }
        System.out.println(" " + angkaRandom);
        
        if(angkaRandom%2==0){
            directory = "src/img/1.jpg";
            warna = "#65ddc0";
        }
        if(angkaRandom%2==0){
            directory = "src/img/2.jpg";
            warna = "#ffd51e";
        }
        if(angkaRandom%2==0){
            directory = "src/img/3.jpg";
            warna = "#a3660c";
        }
        if(angkaRandom%2==0){
            directory = "src/img/4.jpg";
            warna = "#86c440";
        }
        if(angkaRandom%2==0){
            directory = "src/img/5.jpg";
            warna = "#f06c75";
        }
        else{
            directory = "src/img/5.jpg";
            warna = "#f06c75";
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cekAngka().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonReset;
    private javax.swing.JButton jButtonTebak;
    private javax.swing.JLabel jLabelAngkaAtas;
    private javax.swing.JLabel jLabelAngkaBawah;
    private javax.swing.JLabel jLabelCard;
    private javax.swing.JLabel jLabelInputAngka;
    private javax.swing.JLabel jLabelTebak;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanelCard;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextAreaOutput;
    private javax.swing.JTextField jTextFieldInputAngka;
    // End of variables declaration//GEN-END:variables
}
