/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package modultiga;
import java.awt.Color;
import javax.swing.ImageIcon;

/**
 *
 * @author THINKPAD
 */
public class Apotek extends javax.swing.JFrame {
     // Data obat
    private String[] namaObat = {
        "Paracetamol", "Ibuprofen", "Amoxicillin", "Antasida", "Loratadine","Loratadine",
        "Dexamethasone", "Cetrizine", "Salbutamol", "Mefenamic Acid", "Betadine"
    };
     private String[] gejalaObat = {
        "Demam", "Nyeri", "Infeksi", "Maag", "Alergi","Asma",
        "Radang", "Alergi", "Asma", "Sakit Kepala", "Luka"
    };
//     Data Harga
     private double[] hargaObat = {
        15000, 20000, 30000, 12000, 18000,18000,
        25000, 17000, 27000, 22000, 10000
    };
//    Data Gambar
      private ImageIcon[] gambarObat = {
          new ImageIcon(getClass().getResource("/images/paracetamol1.png")),
          new ImageIcon(getClass().getResource("/images/ibuprofen1.png")),
          new ImageIcon(getClass().getResource("/images/amoxicilin1.png")),
          new ImageIcon(getClass().getResource("/images/antasida1.png")),
          new ImageIcon(getClass().getResource("/images/loratadine1.png")),
          new ImageIcon(getClass().getResource("/images/loratadine1.png")),
          new ImageIcon(getClass().getResource("/images/dexamethasone1.png")),
          new ImageIcon(getClass().getResource("/images/cetrizine1.png")),
          new ImageIcon(getClass().getResource("/images/salbutamol1.png")),
          new ImageIcon(getClass().getResource("/images/mefenamic1.png")),
          new ImageIcon(getClass().getResource("/images/betadine1.png")),
    };
//      Data Panduan
       private String[] panduanObat = {
        "1-2 tablet setiap 4-6 jam untuk demam atau sakit kepala",
        "1-2 tablet setiap 6-8 jam untuk mengurangi nyeri",
        "3 kali sehari, 1 kapsul untuk infeksi bakteri",
        "Diminum 30 menit sebelum makan",
        "1 tablet sehari untuk meredakan gejala alergi",
        "1 tablet sehari untuk meredakan gejala alergi",
        "1 tablet sehari atau sesuai resep dokter untuk radang",
        "1 tablet sehari untuk alergi atau gatal-gatal",
        "Gunakan inhaler sesuai dosis yang dianjurkan oleh dokter",
        "1 tablet setiap 6 jam untuk mengurangi nyeri",
        "Oleskan pada area luka yang telah dibersihkan, 1-2 kali sehari"
    };
    /**
     * Creates new form Apotek
     */
    public Apotek() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        groupObat = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        comboGejala = new javax.swing.JComboBox<>();
        btnCek = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        labelDetail = new javax.swing.JLabel();
        labelGambar = new javax.swing.JLabel();
        labelNama = new javax.swing.JLabel();
        labelGejala = new javax.swing.JLabel();
        labelHarga = new javax.swing.JLabel();
        labelPanduan = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        radio1 = new javax.swing.JRadioButton();
        radio2 = new javax.swing.JRadioButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(65, 152, 178));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel3.setFont(new java.awt.Font("News706 BT", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Selamat Datang di Newrom Medical");
        jPanel2.add(jLabel3, new java.awt.GridBagConstraints());

        jLabel5.setFont(new java.awt.Font("News706 BT", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("\"Let's Check Up Your Medicine\"");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel2.add(jLabel5, gridBagConstraints);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 850, 70);

        jPanel3.setBackground(new java.awt.Color(65, 152, 178));
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 10));

        jLabel1.setFont(new java.awt.Font("News706 BT", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Pilih Gejala");
        jPanel3.add(jLabel1);

        comboGejala.setFont(new java.awt.Font("News706 BT", 0, 12)); // NOI18N
        comboGejala.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Pilih Gejala--", "Demam", "Nyeri", "Infeksi", "Maag", "Alergi", "Radang", "Asma", "Sakit Kepala", "Luka" }));
        comboGejala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboGejalaActionPerformed(evt);
            }
        });
        jPanel3.add(comboGejala);

        btnCek.setFont(new java.awt.Font("News706 BT", 0, 12)); // NOI18N
        btnCek.setText("Cek");
        btnCek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCekActionPerformed(evt);
            }
        });
        jPanel3.add(btnCek);

        btnBack.setFont(new java.awt.Font("News706 BT", 0, 12)); // NOI18N
        btnBack.setText("Kembali");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel3.add(btnBack);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(340, 100, 390, 50);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new java.awt.GridBagLayout());

        labelDetail.setFont(new java.awt.Font("News706 BT", 0, 24)); // NOI18N
        labelDetail.setText("Detail Obat");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        jPanel5.add(labelDetail, gridBagConstraints);

        labelGambar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 31;
        jPanel5.add(labelGambar, gridBagConstraints);

        labelNama.setFont(new java.awt.Font("News706 BT", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel5.add(labelNama, gridBagConstraints);

        labelGejala.setFont(new java.awt.Font("News706 BT", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel5.add(labelGejala, gridBagConstraints);

        labelHarga.setFont(new java.awt.Font("News706 BT", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel5.add(labelHarga, gridBagConstraints);

        labelPanduan.setFont(new java.awt.Font("News706 BT", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel5.add(labelPanduan, gridBagConstraints);

        jPanel1.add(jPanel5);
        jPanel5.setBounds(110, 160, 450, 360);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new java.awt.GridLayout(2, 1, 2, 0));

        groupObat.add(radio1);
        radio1.setFont(new java.awt.Font("News706 BT", 0, 12)); // NOI18N
        radio1.setText("obat 1");
        radio1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radio1ItemStateChanged(evt);
            }
        });
        radio1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                radio1StateChanged(evt);
            }
        });
        radio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio1ActionPerformed(evt);
            }
        });
        jPanel4.add(radio1);

        groupObat.add(radio2);
        radio2.setFont(new java.awt.Font("News706 BT", 0, 12)); // NOI18N
        radio2.setText("obat 2");
        radio2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radio2ItemStateChanged(evt);
            }
        });
        radio2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                radio2StateChanged(evt);
            }
        });
        radio2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio2ActionPerformed(evt);
            }
        });
        jPanel4.add(radio2);

        jScrollPane1.setViewportView(jPanel4);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(580, 160, 150, 340);

        jPanel6.setBackground(new java.awt.Color(65, 152, 178));
        jPanel6.setLayout(null);

        jPanel9.setLayout(null);

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\THINKPAD\\Downloads\\waveob.png")); // NOI18N
        jPanel9.add(jLabel6);
        jLabel6.setBounds(0, 0, 650, 80);

        jPanel6.add(jPanel9);
        jPanel9.setBounds(100, 0, 650, 70);

        jPanel1.add(jPanel6);
        jPanel6.setBounds(0, 530, 850, 70);

        jPanel7.setLayout(new javax.swing.OverlayLayout(jPanel7));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\THINKPAD\\Downloads\\bannerdiri.png")); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel7.add(jLabel2);

        jPanel1.add(jPanel7);
        jPanel7.setBounds(0, 70, 100, 460);

        jPanel8.setLayout(new javax.swing.OverlayLayout(jPanel8));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\THINKPAD\\Downloads\\bannerdiri.png")); // NOI18N
        jPanel8.add(jLabel4);

        jPanel1.add(jPanel8);
        jPanel8.setBounds(750, 70, 100, 460);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 850, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboGejalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboGejalaActionPerformed
        // TODO add your handling code here:
        String selectedGejala = (String) comboGejala.getSelectedItem();
        // Reset semua pilihan
        radio1.setSelected(false);
        radio2.setSelected(false);
        radio1.setVisible(false);
        radio2.setVisible(false);
        radio1.setForeground(Color.BLACK);
        radio2.setForeground(Color.BLACK); 
        // Menampilkan radio button yang sesuai dengan gejala yang dipilih
        int count = 0; // Hitung jumlah obat yang sesuai dengan gejala
        for (int i = 0; i < gejalaObat.length; i++) {
            if (gejalaObat[i].equals(selectedGejala)) {
                if (count == 0) {
                    radio1.setText(namaObat[i]);
                    radio1.setIcon(gambarObat[i]);  // Set gambar obat ke radio button
                    radio1.setVisible(true); // Tampilkan radio button
                    count++;
                } else if (count == 1) {
                    radio2.setText(namaObat[i]);
                    radio2.setIcon(gambarObat[i]);  // Set gambar obat ke radio button
                    radio2.setVisible(true); // Tampilkan radio button
                    count++;
                }
            }
        }
    }//GEN-LAST:event_comboGejalaActionPerformed

    private void btnCekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCekActionPerformed
        // TODO add your handling code here:
        // Cek radio button mana yang dipilih
        if (radio1.isSelected()) {
            updateLabelInfo(radio1.getText());
        } else if (radio2.isSelected()) {
            updateLabelInfo(radio2.getText());
        }
    }
    private void updateLabelInfo(String namaObatDipilih) {
        for (int j = 0; j < namaObat.length; j++) {
            if (namaObat[j].equals(namaObatDipilih)) {
                labelGambar.setIcon(gambarObat[j]);  // Tampilkan gambar obat
                labelNama.setText("Nama Obat : " + namaObatDipilih);
                labelHarga.setText("Harga: Rp. " + hargaObat[j]);
                labelGejala.setText("Gejala: " + gejalaObat[j]);
                labelPanduan.setText("Panduan: " + panduanObat[j]);
                break;
            }
        }
    }//GEN-LAST:event_btnCekActionPerformed

    private void radio1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_radio1StateChanged
        // TODO add your handling code here:    
    }//GEN-LAST:event_radio1StateChanged

    private void radio1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radio1ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_radio1ItemStateChanged

    private void radio2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radio2ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_radio2ItemStateChanged

    private void radio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio1ActionPerformed
        // TODO add your handling code here:
        radio1.setForeground(Color.BLUE);
        radio2.setForeground(Color.BLACK);
    }//GEN-LAST:event_radio1ActionPerformed

    private void radio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio2ActionPerformed
        // TODO add your handling code here:
        radio2.setForeground(Color.BLUE);
        radio1.setForeground(Color.BLACK);
    }//GEN-LAST:event_radio2ActionPerformed

    private void radio2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_radio2StateChanged
        // TODO add your handling code here:
      
    }//GEN-LAST:event_radio2StateChanged

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        welcome form1 = new welcome();
        form1.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Apotek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Apotek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Apotek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Apotek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Apotek().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCek;
    private javax.swing.JComboBox<String> comboGejala;
    private javax.swing.ButtonGroup groupObat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelDetail;
    private javax.swing.JLabel labelGambar;
    private javax.swing.JLabel labelGejala;
    private javax.swing.JLabel labelHarga;
    private javax.swing.JLabel labelNama;
    private javax.swing.JLabel labelPanduan;
    private javax.swing.JRadioButton radio1;
    private javax.swing.JRadioButton radio2;
    // End of variables declaration//GEN-END:variables
}
