/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package modul4;

import javax.swing.JOptionPane;
import javax.swing.DefaultListModel;
import java.util.Random;

public class PermainanTebakAngka extends javax.swing.JFrame {
    // Variabel global
    Random rand = new Random();
    int targetangka = rand.nextInt(100)+1;
    
    private int targetAngka;
    private int kesempatanTebakan = 10;
    private DefaultListModel<String> listScoreModel = new DefaultListModel<>(); // Model untuk JList
    private int skor = 0;
    
    /**
     * Creates new form PermainanTebakAngka
     */
    public PermainanTebakAngka() {
        initComponents();
        setTargetAngka(); // Atur target angka acak
        listScore.setModel(listScoreModel); // Set model ke JList
    }
    
   // Metode untuk mengacak angka target
    private void setTargetAngka() {
        Random rand = new Random();
        targetAngka = rand.nextInt(100) + 1; // Angka antara 1-100
        kesempatanTebakan = 10; // Reset kesempatan
        skor = 0; // Reset skor
        btnTebak.setText("Tebak (" + kesempatanTebakan + ")");
        tfScore.setText("Score: " + skor);
        tfInputAngkaTebakan.setText(""); // Kosongkan input tebakan
        tfCek.setText(""); // Kosongkan hasil cek tebakan
        JOptionPane.showMessageDialog(this, "Permainan dimulai! Silakan coba tebak angka.");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        labelCobaTebak = new javax.swing.JLabel();
        labelCek = new javax.swing.JLabel();
        labelScore = new javax.swing.JLabel();
        tfInputAngkaTebakan = new javax.swing.JTextField();
        tfCek = new javax.swing.JTextField();
        tfScore = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        btnTebak = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnStart = new javax.swing.JButton();
        labelBackgroundPermainan = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listScore = new javax.swing.JList<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        labelBackgroundScore = new javax.swing.JLabel();

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modul4/Background.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modul4/Background.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modul4/Score2.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(245, 235, 226));

        jTabbedPane1.setBackground(new java.awt.Color(250, 241, 232));

        jPanel1.setBackground(new java.awt.Color(247, 236, 224));

        jPanel3.setBackground(new java.awt.Color(247, 236, 224));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelCobaTebak.setFont(new java.awt.Font("Hobo Std", 0, 18)); // NOI18N
        labelCobaTebak.setForeground(new java.awt.Color(204, 0, 0));
        labelCobaTebak.setText("Coba Tebak");
        jPanel3.add(labelCobaTebak, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        labelCek.setFont(new java.awt.Font("Hobo Std", 0, 18)); // NOI18N
        labelCek.setForeground(new java.awt.Color(204, 0, 0));
        labelCek.setText("Cek");
        jPanel3.add(labelCek, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, -1, -1));

        labelScore.setFont(new java.awt.Font("Hobo Std", 0, 18)); // NOI18N
        labelScore.setForeground(new java.awt.Color(204, 0, 0));
        labelScore.setText("Score");
        jPanel3.add(labelScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, -1, 20));

        tfInputAngkaTebakan.setFont(new java.awt.Font("Hobo Std", 0, 14)); // NOI18N
        tfInputAngkaTebakan.setForeground(new java.awt.Color(204, 0, 0));
        tfInputAngkaTebakan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfInputAngkaTebakanActionPerformed(evt);
            }
        });
        jPanel3.add(tfInputAngkaTebakan, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 190, -1));

        tfCek.setEditable(false);
        tfCek.setFont(new java.awt.Font("Hobo Std", 0, 14)); // NOI18N
        tfCek.setForeground(new java.awt.Color(204, 0, 0));
        jPanel3.add(tfCek, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 190, -1));

        tfScore.setEditable(false);
        tfScore.setFont(new java.awt.Font("Hobo Std", 0, 14)); // NOI18N
        tfScore.setForeground(new java.awt.Color(204, 0, 0));
        jPanel3.add(tfScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 190, -1));

        jPanel4.setBackground(new java.awt.Color(245, 236, 227));
        jPanel4.setLayout(new java.awt.GridLayout(1, 0, 5, 5));

        btnTebak.setFont(new java.awt.Font("Hobo Std", 0, 14)); // NOI18N
        btnTebak.setForeground(new java.awt.Color(204, 0, 0));
        btnTebak.setText("Tebak");
        btnTebak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTebakActionPerformed(evt);
            }
        });
        jPanel4.add(btnTebak);

        btnReset.setFont(new java.awt.Font("Hobo Std", 0, 14)); // NOI18N
        btnReset.setForeground(new java.awt.Color(204, 0, 0));
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        jPanel4.add(btnReset);

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, 220, 30));

        jLabel6.setFont(new java.awt.Font("Hobo Std", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 0, 0));
        jLabel6.setText("GAME");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, -1));

        jLabel7.setFont(new java.awt.Font("Hobo Std", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 0, 0));
        jLabel7.setText("TEBAK");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, -1, -1));

        jLabel8.setFont(new java.awt.Font("Hobo Std", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 0, 0));
        jLabel8.setText("ANGKA");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText(":");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 20, 20));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText(":");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 10, 20));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText(":");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 10, 20));

        jLabel12.setFont(new java.awt.Font("Hobo Std", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 0, 0));
        jLabel12.setText("Mainkan Dan Lihat Seberapa Tajam Tebakanmu!");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        jLabel13.setFont(new java.awt.Font("Hobo Std", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 0, 0));
        jLabel13.setText("Punya Keberanian? ");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 500, -1, -1));

        jLabel14.setFont(new java.awt.Font("Hobo Std", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 0, 0));
        jLabel14.setText("Tebak Angka 01 Hingga 100 Dan Raih Skor tertinggi! ");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 530, -1, -1));

        btnStart.setFont(new java.awt.Font("Hobo Std", 0, 14)); // NOI18N
        btnStart.setForeground(new java.awt.Color(204, 0, 0));
        btnStart.setText("Start");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });
        jPanel3.add(btnStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 400, 80, 30));

        labelBackgroundPermainan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modul4/Background.jpg"))); // NOI18N
        labelBackgroundPermainan.setText("jLabel20");
        jPanel3.add(labelBackgroundPermainan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Permainan", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listScore.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listScore);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 190, 220));

        jLabel15.setFont(new java.awt.Font("Hobo Std", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 0, 0));
        jLabel15.setText("Rekam Jejak Kemenanganmu! ");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 470, -1, -1));

        jLabel16.setFont(new java.awt.Font("Hobo Std", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 0, 0));
        jLabel16.setText("Tinggalkan Jejak Dengan Skor Tertinggi!");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 500, -1, -1));

        jLabel17.setFont(new java.awt.Font("Hobo Std", 1, 36)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 0, 0));
        jLabel17.setText("GAME");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, -1));

        jLabel18.setFont(new java.awt.Font("Hobo Std", 1, 36)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 0, 0));
        jLabel18.setText("TEBAK");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, -1, -1));

        jLabel19.setFont(new java.awt.Font("Hobo Std", 1, 36)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(204, 0, 0));
        jLabel19.setText("ANGKA");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, -1, -1));

        labelBackgroundScore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modul4/Background.jpg"))); // NOI18N
        labelBackgroundScore.setText("jLabel5");
        jPanel2.add(labelBackgroundScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 1230));

        jTabbedPane1.addTab("Score", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 661, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfInputAngkaTebakanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfInputAngkaTebakanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfInputAngkaTebakanActionPerformed

    private void btnTebakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTebakActionPerformed

        try {
        int tebakan = Integer.parseInt(tfInputAngkaTebakan.getText()); // Ambil input dari tfInputAngkaTebakan
        
        if (tebakan < 1 || tebakan > 100) {
            JOptionPane.showMessageDialog(this, "Masukkan angka antara 01 hingga 100!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            tfInputAngkaTebakan.setText(""); 
            return; 
        }
        
        if (tebakan == targetAngka) {
        if (tebakan == targetAngka) {
    skor = kesempatanTebakan * 10; // Hitung skor
    tfScore.setText("Score: " + skor); // Tampilkan skor di tfScore
    String nama = JOptionPane.showInputDialog(this, "Anda berhasil! Masukkan nama Anda:");
    
    // Cek jika nama tidak null atau kosong
    if (nama != null && !nama.trim().isEmpty()) {
        listScoreModel.addElement(nama + " - Score: " + skor); // Tambah skor ke model list
    } else {
        JOptionPane.showMessageDialog(this, "Nama tidak dimasukkan. Skor tidak disimpan.", "Peringatan", JOptionPane.WARNING_MESSAGE);
    }
    
    setTargetAngka(); // Reset permainan setelah tebakan benar
}

        } else {
            kesempatanTebakan--;
            skor = kesempatanTebakan * 10; // Update skor berdasarkan kesempatan tersisa
            tfScore.setText("Score: " + skor); // Tampilkan skor setiap kali kesempatan berkurang
            btnTebak.setText("Tebak (" + kesempatanTebakan + ")");

            if (kesempatanTebakan == 0) {
                JOptionPane.showMessageDialog(this, "Anda Gagal! Permainan direset.");
                setTargetAngka();
            } else if (tebakan < targetAngka) {
                tfCek.setText("Angka Lebih Besar!");
            } else {
                tfCek.setText("Angka Lebih Kecil!");
            }
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Masukkan angka yang valid!", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnTebakActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        setTargetAngka(); // Reset permainan
        tfInputAngkaTebakan.setText("");
        tfCek.setText("");
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        targetAngka = rand.nextInt(100) + 1;
        System.out.println(targetAngka);
        JOptionPane.showMessageDialog(this, "Apakah Anda yakin ingin memulainya!", "Peringatan", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_btnStartActionPerformed
 

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PermainanTebakAngka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PermainanTebakAngka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PermainanTebakAngka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PermainanTebakAngka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PermainanTebakAngka().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnStart;
    private javax.swing.JButton btnTebak;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel labelBackgroundPermainan;
    private javax.swing.JLabel labelBackgroundScore;
    private javax.swing.JLabel labelCek;
    private javax.swing.JLabel labelCobaTebak;
    private javax.swing.JLabel labelScore;
    private javax.swing.JList<String> listScore;
    private javax.swing.JTextField tfCek;
    private javax.swing.JTextField tfInputAngkaTebakan;
    private javax.swing.JTextField tfScore;
    // End of variables declaration//GEN-END:variables
}
