/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package modul4;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
/**
 *
 * @author THINKPAD
 */
public class TebakAngka extends javax.swing.JFrame {
    // icon JOption
    ImageIcon icon_gagal = new ImageIcon(getClass().getResource("iconGagal.png"));
    ImageIcon icon_coba = new ImageIcon(getClass().getResource("iconCoba.png"));
    ImageIcon icon_selamat = new ImageIcon(getClass().getResource("iconSelamat.png"));
    ImageIcon icon_warning = new ImageIcon(getClass().getResource("iconWarning.png"));
    // Deklarasi atribut
    private int angkaTebakan;
    private int kesempatan;
    private int skor;
    private int batasBawah = 0;
    private int batasAtas = 100;
    private ArrayList<String> skorRiwayat = new ArrayList<>();
    /**
     * Creates new form TebakAngka
     */
    public TebakAngka() {
        initComponents();
        angkaTebakan = new Random().nextInt(100) + 1;
        kesempatan = 10;
        skor = 0;
        batasBawah = 0;
        batasAtas = 100;
        tebak.setText("TEBAK (" + kesempatan + ")");
        fieldTebak.setText("");
        fieldHasil.setText("");
        fieldScore.setText("");
    }
    // method reset   
    private void resetGame() {
        angkaTebakan = new Random().nextInt(100) + 1;
        kesempatan = 10;
        skor = 0;
        batasBawah = 0;
        batasAtas = 100;
        tebak.setText("TEBAK (" + kesempatan + ")");
        fieldTebak.setText("");
        fieldHasil.setText("");
        fieldScore.setText("");
    }
    // method skor    
    private void updateScoreRiwayat() {
        String riwayat = "";
        int indeks = 1;
        for (String s : skorRiwayat) {
            riwayat += indeks++ +". " + s + "\n";
        }
        scoreRiwayatArea.setText(riwayat);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tabbedPaneCustom1 = new raven.tabbed.TabbedPaneCustom();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fieldTebak = new javax.swing.JTextField();
        fieldHasil = new javax.swing.JTextField();
        fieldScore = new javax.swing.JTextField();
        tebak = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        scoreRiwayatArea = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabbedPaneCustom1.setBackground(new java.awt.Color(0, 0, 0));
        tabbedPaneCustom1.setForeground(new java.awt.Color(255, 255, 255));
        tabbedPaneCustom1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        tabbedPaneCustom1.setSelectedColor(new java.awt.Color(0, 102, 102));
        tabbedPaneCustom1.setUnselectedColor(new java.awt.Color(254, 199, 11));

        jPanel4.setBackground(new java.awt.Color(0, 124, 107));
        jPanel4.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 124, 107));
        jLabel3.setText("Hasil");
        jPanel4.add(jLabel3);
        jLabel3.setBounds(80, 150, 50, 30);

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 124, 107));
        jLabel4.setText("Score");
        jPanel4.add(jLabel4);
        jLabel4.setBounds(80, 200, 60, 30);

        fieldTebak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldTebakActionPerformed(evt);
            }
        });
        jPanel4.add(fieldTebak);
        fieldTebak.setBounds(190, 100, 270, 30);

        fieldHasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldHasilActionPerformed(evt);
            }
        });
        jPanel4.add(fieldHasil);
        fieldHasil.setBounds(190, 150, 270, 30);

        fieldScore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldScoreActionPerformed(evt);
            }
        });
        jPanel4.add(fieldScore);
        fieldScore.setBounds(190, 200, 270, 30);

        tebak.setBackground(new java.awt.Color(0, 124, 107));
        tebak.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        tebak.setForeground(new java.awt.Color(254, 199, 11));
        tebak.setText("Tebak");
        tebak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tebakActionPerformed(evt);
            }
        });
        jPanel4.add(tebak);
        tebak.setBounds(50, 240, 110, 40);

        reset.setBackground(new java.awt.Color(0, 124, 107));
        reset.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        reset.setForeground(new java.awt.Color(254, 199, 11));
        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        jPanel4.add(reset);
        reset.setBounds(400, 240, 100, 40);

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 124, 107));
        jLabel2.setText("Tebakanmu");
        jPanel4.add(jLabel2);
        jLabel2.setBounds(80, 100, 100, 30);

        jLabel7.setIcon(new javax.swing.ImageIcon("D:\\modul pemvis\\modul 4\\img\\avengacha (3).gif")); // NOI18N
        jLabel7.setText("jLabel7");
        jPanel4.add(jLabel7);
        jLabel7.setBounds(0, 0, 550, 350);

        tabbedPaneCustom1.addTab("Games", jPanel4);

        jPanel5.setBackground(new java.awt.Color(0, 124, 107));
        jPanel5.setLayout(null);

        scoreRiwayatArea.setColumns(20);
        scoreRiwayatArea.setRows(5);
        jScrollPane1.setViewportView(scoreRiwayatArea);

        jPanel5.add(jScrollPane1);
        jScrollPane1.setBounds(70, 80, 410, 240);

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(254, 199, 11));
        jLabel5.setText("Score");
        jPanel5.add(jLabel5);
        jLabel5.setBounds(240, 40, 70, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\modul pemvis\\modul 4\\img\\avengachadf (1).png")); // NOI18N
        jPanel5.add(jLabel1);
        jLabel1.setBounds(0, 0, 550, 350);

        tabbedPaneCustom1.addTab("Score", jPanel5);

        jPanel1.add(tabbedPaneCustom1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 550, 390));

        jPanel2.setLayout(new javax.swing.OverlayLayout(jPanel2));

        jLabel6.setIcon(new javax.swing.ImageIcon("D:\\modul pemvis\\modul 4\\img\\imgAven\\aven.png")); // NOI18N
        jPanel2.add(jLabel6);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 110));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 470));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void fieldTebakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldTebakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldTebakActionPerformed

    private void tebakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tebakActionPerformed
        // TODO add your handling code here:
        if (kesempatan > 0) {
            try {
                int tebakan = Integer.parseInt(fieldTebak.getText());
//                System.out.println(angkaTebakan);
                kesempatan--;
                if (tebakan == angkaTebakan) {
                    skor = kesempatan * 10;
                    fieldHasil.setText("Anda Berhasil!");
                    fieldScore.setText(String.valueOf(skor));
                    String nama = (String) JOptionPane.showInputDialog(this, "Masukkan Nama:","Pemenang",JOptionPane.INFORMATION_MESSAGE,icon_selamat,null,null);
                    if (nama != null && !nama.isEmpty()) {
                        skorRiwayat.add(nama + "  -- Score --  : " + skor);
                        updateScoreRiwayat();
                        resetGame();
                    }
                } else {
                    if (tebakan < angkaTebakan) {
                        fieldHasil.setText("Tebakan terlalu kecil!");
                        batasBawah = Math.max(batasBawah, tebakan + 1);
                        fieldTebak.setText("");
                    } else {
                        fieldHasil.setText("Tebakan terlalu besar!");
                        batasAtas = Math.min(batasAtas, tebakan - 1);
                        fieldTebak.setText("");
                    }
                    JOptionPane.showMessageDialog(this, "Coba lagi! Rentang tebakan: " + batasBawah + " - " + batasAtas,"Try Again",JOptionPane.WARNING_MESSAGE,icon_coba);
                    tebak.setText("TEBAK (" + kesempatan + ")");
                }
                if (kesempatan == 0 && tebakan != angkaTebakan) {
                    JOptionPane.showMessageDialog(this, "Anda Gagal! Angka tebakannya adalah " + angkaTebakan, "Game Over", JOptionPane.ERROR_MESSAGE,icon_gagal);
                    resetGame();
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Ini Tebak Angka!!!", "Error", JOptionPane.ERROR_MESSAGE,icon_warning);
            }
        }
    }//GEN-LAST:event_tebakActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        resetGame(); 
    }//GEN-LAST:event_resetActionPerformed
    
    private void fieldHasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldHasilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldHasilActionPerformed

    private void fieldScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldScoreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldScoreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TebakAngka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TebakAngka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TebakAngka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TebakAngka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TebakAngka().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fieldHasil;
    private javax.swing.JTextField fieldScore;
    private javax.swing.JTextField fieldTebak;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton reset;
    private javax.swing.JTextArea scoreRiwayatArea;
    private raven.tabbed.TabbedPaneCustom tabbedPaneCustom1;
    private javax.swing.JButton tebak;
    // End of variables declaration//GEN-END:variables
}
