


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import javax.swing.JOptionPane;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.Icon;
/**
 *
 * @author AMANDA AULIA
 */
public class JFrame1 extends javax.swing.JFrame {

    /**
     * Creates new form JFrame1
     */
    public JFrame1() {
        initComponents();
        TfJumlah.setEditable(false);
        TfTotal.setEditable(false);
        TfDiskon.setEditable(false);
        TfKembalian.setEditable(false);
        
//        TfCash.addKeyListener(new KeyAdapter() {
//            public void keyReleased(KeyEvent e) {
//                penghitungan();
//            }
//        });
        TfJumlah.setText("0");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabelLogo = new javax.swing.JLabel();
        jLabelJudul = new javax.swing.JLabel();
        jLabelMenu = new javax.swing.JLabel();
        RbMenu1 = new javax.swing.JRadioButton();
        RbMenu2 = new javax.swing.JRadioButton();
        RbMenu3 = new javax.swing.JRadioButton();
        RbMenu4 = new javax.swing.JRadioButton();
        RbMenu5 = new javax.swing.JRadioButton();
        RbMenu6 = new javax.swing.JRadioButton();
        jLabelGaris1 = new javax.swing.JLabel();
        jLabelToping = new javax.swing.JLabel();
        RbToping1 = new javax.swing.JRadioButton();
        RbToping2 = new javax.swing.JRadioButton();
        RbToping3 = new javax.swing.JRadioButton();
        RbToping4 = new javax.swing.JRadioButton();
        jLabelGrais2 = new javax.swing.JLabel();
        jLabelJumlah = new javax.swing.JLabel();
        jButtonKurang = new javax.swing.JButton();
        TfJumlah = new javax.swing.JTextField();
        jButtonTambah = new javax.swing.JButton();
        jLabelTotal = new javax.swing.JLabel();
        TfTotal = new javax.swing.JTextField();
        jLabelCash = new javax.swing.JLabel();
        TfCash = new javax.swing.JTextField();
        jButtonHitung = new javax.swing.JButton();
        jLabelDiskon = new javax.swing.JLabel();
        TfDiskon = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        TfKembalian = new javax.swing.JTextField();
        jButtonBatal = new javax.swing.JButton();
        jButtonReset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        jLabelLogo.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Downloads\\brownies2.png")); // NOI18N

        jLabelJudul.setFont(new java.awt.Font("Snap ITC", 0, 48)); // NOI18N
        jLabelJudul.setText("Brownies");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabelLogo)
                .addGap(42, 42, 42)
                .addComponent(jLabelJudul)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabelLogo))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabelJudul)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelMenu.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        jLabelMenu.setText("Menu Brownies");

        buttonGroup1.add(RbMenu1);
        RbMenu1.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        RbMenu1.setText("Original Rp.20000");
        RbMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbMenu1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(RbMenu2);
        RbMenu2.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        RbMenu2.setText("Tiramisu Rp.25000");

        buttonGroup1.add(RbMenu3);
        RbMenu3.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        RbMenu3.setText("Banana Rp.30000");

        buttonGroup1.add(RbMenu4);
        RbMenu4.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        RbMenu4.setText("Stawberry Rp.35000");

        buttonGroup1.add(RbMenu5);
        RbMenu5.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        RbMenu5.setText("Blueberry Rp.40000");

        buttonGroup1.add(RbMenu6);
        RbMenu6.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        RbMenu6.setText("Pandan Rp.45000");

        jLabelGaris1.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Downloads\\downloadgaris .png")); // NOI18N

        jLabelToping.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        jLabelToping.setText("Topping");

        buttonGroup2.add(RbToping1);
        RbToping1.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        RbToping1.setText("Keju Rp.5000");

        buttonGroup2.add(RbToping2);
        RbToping2.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        RbToping2.setText("Oreo Rp.7000");

        buttonGroup2.add(RbToping3);
        RbToping3.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        RbToping3.setText("Kacang Rp.10000");

        buttonGroup2.add(RbToping4);
        RbToping4.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        RbToping4.setText("No Toping");

        jLabelGrais2.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Downloads\\downloadgaris .png")); // NOI18N

        jLabelJumlah.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        jLabelJumlah.setText("Jumlah");

        jButtonKurang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonKurang.setText("-");
        jButtonKurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKurangActionPerformed(evt);
            }
        });

        jButtonTambah.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonTambah.setText("+");
        jButtonTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTambahActionPerformed(evt);
            }
        });

        jLabelTotal.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        jLabelTotal.setText("Total");

        jLabelCash.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        jLabelCash.setText("Cash");

        TfCash.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TfCashKeyReleased(evt);
            }
        });

        jButtonHitung.setFont(new java.awt.Font("Snap ITC", 0, 12)); // NOI18N
        jButtonHitung.setForeground(new java.awt.Color(0, 51, 0));
        jButtonHitung.setText("Hitung");
        jButtonHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHitungActionPerformed(evt);
            }
        });

        jLabelDiskon.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        jLabelDiskon.setText("Diskon");

        jLabel1.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        jLabel1.setText("Kembalian");

        jButtonBatal.setFont(new java.awt.Font("Snap ITC", 0, 14)); // NOI18N
        jButtonBatal.setText("Batal");
        jButtonBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBatalActionPerformed(evt);
            }
        });

        jButtonReset.setFont(new java.awt.Font("Snap ITC", 0, 14)); // NOI18N
        jButtonReset.setText("Reset");
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jLabelGaris1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelJumlah)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonKurang)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TfJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonTambah))
                            .addComponent(jLabelCash)
                            .addComponent(TfCash))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabelDiskon)
                            .addComponent(TfDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TfKembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonHitung))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonBatal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonReset)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(RbMenu1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(RbMenu4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RbMenu2)
                                    .addComponent(RbMenu3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RbMenu6)
                                    .addComponent(RbMenu5))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelMenu)
                            .addComponent(jLabelToping)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jLabelGrais2))
                            .addComponent(jLabelTotal)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RbToping1)
                                    .addComponent(RbToping2))
                                .addGap(93, 93, 93)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RbToping4)
                                    .addComponent(RbToping3))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelMenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RbMenu1)
                    .addComponent(RbMenu4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RbMenu2)
                    .addComponent(RbMenu5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RbMenu3)
                    .addComponent(RbMenu6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelGaris1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelToping)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RbToping1)
                    .addComponent(RbToping3))
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RbToping2)
                    .addComponent(RbToping4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelGrais2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelJumlah)
                    .addComponent(jLabelDiskon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonKurang)
                    .addComponent(TfJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonTambah)
                    .addComponent(TfDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelTotal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonHitung))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCash)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TfCash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TfKembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBatal)
                    .addComponent(jButtonReset))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void penghitungan() {
        try {
            double hargasetelahdiskon = Double.parseDouble(TfTotal.getText());
            double uangmasuk = Double.parseDouble(TfCash.getText());
            double kembalian = uangmasuk - hargasetelahdiskon;

            if (kembalian >= 0) {
                TfKembalian.setText(String.valueOf(kembalian));
            } else {
                TfKembalian.setText("Uang Tidak Cukup");
            }
        } catch (NumberFormatException e) { 
            TfKembalian.setText("Input Tidak Sesuai"); 
        }
    }
    private void jButtonTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTambahActionPerformed
        // TODO add your handling code here:
        int jumlah = Integer.parseInt(TfJumlah.getText());
        jumlah += 1;
        TfJumlah.setText(String.valueOf(jumlah));
    }//GEN-LAST:event_jButtonTambahActionPerformed

    private void jButtonKurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKurangActionPerformed
        // TODO add your handling code here:
        if(Integer.parseInt(TfJumlah.getText())>0)
        {
        int jumlah = Integer.parseInt(TfJumlah.getText());
            jumlah -= 1;
            TfJumlah.setText(String.valueOf(jumlah));
        }else{
            TfJumlah.setText("0");
        }
    }//GEN-LAST:event_jButtonKurangActionPerformed

    private void jButtonHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHitungActionPerformed
        // TODO add your handling code here:
        if (buttonGroup1.getSelection() == null) {
            JOptionPane.showMessageDialog(null, "Anda harus memilih menu terlebih dahulu!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        } else if (buttonGroup2.getSelection() == null) {
            JOptionPane.showMessageDialog(null, "Anda harus memilih topping terlebih dahulu!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        } else if (Integer.parseInt(TfJumlah.getText()) <= 0) { 
            JOptionPane.showMessageDialog(null, "Jumlah pembelian harus lebih dari 0!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        } else {
            double harga = 0;
            double diskon = 0;
            double cash = 0;
            double kembalian = 0;
            
            if (RbMenu1.isSelected()){
                String jumlahpesanan = TfJumlah.getText();
                harga += 20000 * Integer.parseInt(jumlahpesanan);
                if (RbToping1.isSelected()){
                    harga += 5000 * Integer.parseInt(jumlahpesanan);
                } else if (RbToping2.isSelected()){
                    harga += 7000 * Integer.parseInt(jumlahpesanan);
                } else if (RbToping3.isSelected()){
                    harga += 10000 * Integer.parseInt(jumlahpesanan);
                } else {
                    harga += 0 * Integer.parseInt(jumlahpesanan);
                }
                TfTotal.setText(String.valueOf(harga));
                    if (harga >= 100000) {
                        diskon = harga * 0.05;
                        TfDiskon.setText(String.valueOf(diskon));
                        harga -= diskon;
                        TfTotal.setText(String.valueOf(harga));
                    } else {
                        TfDiskon.setText("0");
                        TfTotal.setText(String.valueOf(harga));
                    }
            }
            
            if (RbMenu2.isSelected()){
                String jumlahpesanan = TfJumlah.getText();
                harga += 25000 * Integer.parseInt(jumlahpesanan);
                if (RbToping1.isSelected()){
                    harga += 5000 * Integer.parseInt(jumlahpesanan);
                } else if (RbToping2.isSelected()){
                    harga += 7000 * Integer.parseInt(jumlahpesanan);
                } else if (RbToping3.isSelected()){
                    harga += 10000 * Integer.parseInt(jumlahpesanan);
                } else {
                    harga += 0 * Integer.parseInt(jumlahpesanan);
                }
                TfTotal.setText(String.valueOf(harga));
                    if (harga >= 100000) {
                        diskon = harga * 0.05;
                        TfDiskon.setText(String.valueOf(diskon));
                        harga -= diskon;
                        TfTotal.setText(String.valueOf(harga));
                    } else {
                        TfDiskon.setText("0");
                        TfTotal.setText(String.valueOf(harga));
                    }
            }
            if (RbMenu3.isSelected()){
                String jumlahpesanan = TfJumlah.getText();
                harga += 30000 * Integer.parseInt(jumlahpesanan);
                if (RbToping1.isSelected()){
                    harga += 5000 * Integer.parseInt(jumlahpesanan);
                } else if (RbToping2.isSelected()){
                    harga += 7000 * Integer.parseInt(jumlahpesanan);
                } else if (RbToping3.isSelected()){
                    harga += 10000 * Integer.parseInt(jumlahpesanan);
                } else {
                    harga += 0 * Integer.parseInt(jumlahpesanan);
                }
                TfTotal.setText(String.valueOf(harga));
                    if (harga >= 100000) {
                        diskon = harga * 0.05;
                        TfDiskon.setText(String.valueOf(diskon));
                        harga -= diskon;
                        TfTotal.setText(String.valueOf(harga));
                    } else {
                        TfDiskon.setText("0");
                        TfTotal.setText(String.valueOf(harga));
                    }
            }
            if (RbMenu4.isSelected()){
                String jumlahpesanan = TfJumlah.getText();
                harga += 35000 * Integer.parseInt(jumlahpesanan);
                if (RbToping1.isSelected()){
                    harga += 5000 * Integer.parseInt(jumlahpesanan);
                } else if (RbToping2.isSelected()){
                    harga += 7000 * Integer.parseInt(jumlahpesanan);
                } else if (RbToping3.isSelected()){
                    harga += 10000 * Integer.parseInt(jumlahpesanan);
                } else {
                    harga += 0 * Integer.parseInt(jumlahpesanan);
                }
                TfTotal.setText(String.valueOf(harga));
                    if (harga >= 100000) {
                        diskon = harga * 0.05;
                        TfDiskon.setText(String.valueOf(diskon));
                        harga -= diskon;
                        TfTotal.setText(String.valueOf(harga));
                    } else {
                        TfDiskon.setText("0");
                        TfTotal.setText(String.valueOf(harga));
                    }
            }
            if (RbMenu5.isSelected()){
                String jumlahpesanan = TfJumlah.getText();
                harga += 40000 * Integer.parseInt(jumlahpesanan);
                if (RbToping1.isSelected()){
                    harga += 5000 * Integer.parseInt(jumlahpesanan);
                } else if (RbToping2.isSelected()){
                    harga += 7000 * Integer.parseInt(jumlahpesanan);
                } else if (RbToping3.isSelected()){
                    harga += 10000 * Integer.parseInt(jumlahpesanan);
                } else {
                    harga += 0 * Integer.parseInt(jumlahpesanan);
                }
                TfTotal.setText(String.valueOf(harga));
                    if (harga >= 100000) {
                        diskon = harga * 0.05;
                        TfDiskon.setText(String.valueOf(diskon));
                        harga -= diskon;
                        TfTotal.setText(String.valueOf(harga));
                    } else {
                        TfDiskon.setText("0");
                        TfTotal.setText(String.valueOf(harga));
                    }
            }
            if (RbMenu6.isSelected()){
                String jumlahpesanan = TfJumlah.getText();
                harga += 45000 * Integer.parseInt(jumlahpesanan);
                if (RbToping1.isSelected()){
                    harga += 5000 * Integer.parseInt(jumlahpesanan);
                } else if (RbToping2.isSelected()){
                    harga += 7000 * Integer.parseInt(jumlahpesanan);
                } else if (RbToping3.isSelected()){
                    harga += 10000 * Integer.parseInt(jumlahpesanan);
                } else {
                    harga += 0 * Integer.parseInt(jumlahpesanan);
                }
                TfTotal.setText(String.valueOf(harga));
                    if (harga >= 100000) {
                        diskon = harga * 0.05;
                        TfDiskon.setText(String.valueOf(diskon));
                        harga -= diskon;
                        TfTotal.setText(String.valueOf(harga));
                    } else {
                        TfDiskon.setText("0");
                        TfTotal.setText(String.valueOf(harga));
                    }
                    
            }
         }
    }//GEN-LAST:event_jButtonHitungActionPerformed

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
        // TODO add your handling code here:
        buttonGroup1.clearSelection();
        buttonGroup2.clearSelection();
        int jumlah = 0;
        TfJumlah.setText(String.valueOf(jumlah)); //Mmengatur TfJumlah untuk menampilkan nilai 0
        TfTotal.setText("");
        TfDiskon.setText("");
        TfCash.setText("");
        TfKembalian.setText("");
        TfTotal.setText(""); 
        
       
        Icon iconSukses = new javax.swing.ImageIcon(getClass().getResource("icon_oke.png"));
        JOptionPane.showMessageDialog(null, "Sukses Menghapus Data!", "Success", JOptionPane.INFORMATION_MESSAGE, iconSukses);
    }//GEN-LAST:event_jButtonResetActionPerformed

    private void jButtonBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBatalActionPerformed
        // TODO add your handling code here
        int keluar = JOptionPane.showConfirmDialog(null,"Anda Yakin Ingin Keluar Program?","Keluar",JOptionPane.YES_NO_OPTION);
        if (keluar == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jButtonBatalActionPerformed

    private void RbMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RbMenu1ActionPerformed

    private void TfCashKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfCashKeyReleased
        // TODO add your handling code here:
        penghitungan();
    }//GEN-LAST:event_TfCashKeyReleased
    
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RbMenu1;
    private javax.swing.JRadioButton RbMenu2;
    private javax.swing.JRadioButton RbMenu3;
    private javax.swing.JRadioButton RbMenu4;
    private javax.swing.JRadioButton RbMenu5;
    private javax.swing.JRadioButton RbMenu6;
    private javax.swing.JRadioButton RbToping1;
    private javax.swing.JRadioButton RbToping2;
    private javax.swing.JRadioButton RbToping3;
    private javax.swing.JRadioButton RbToping4;
    private javax.swing.JTextField TfCash;
    private javax.swing.JTextField TfDiskon;
    private javax.swing.JTextField TfJumlah;
    private javax.swing.JTextField TfKembalian;
    private javax.swing.JTextField TfTotal;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButtonBatal;
    private javax.swing.JButton jButtonHitung;
    private javax.swing.JButton jButtonKurang;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JButton jButtonTambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelCash;
    private javax.swing.JLabel jLabelDiskon;
    private javax.swing.JLabel jLabelGaris1;
    private javax.swing.JLabel jLabelGrais2;
    private javax.swing.JLabel jLabelJudul;
    private javax.swing.JLabel jLabelJumlah;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelMenu;
    private javax.swing.JLabel jLabelToping;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
