/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package modul3.pkg3;

//import javax.swing.Icon;
import javax.swing.JOptionPane;


/**
 *
 * @author User
 */
public class Desain1 extends javax.swing.JFrame {
//    Icon Paramex = new javax.swing.ImageIcon(getClass().getResource("/Modul33/Gambar8.jpg"));

    /**
     * Creates new form Desain1
     */
    public Desain1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanelkir1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        isi1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        isi2 = new javax.swing.JTextField();
        jButton13 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        Kolom1 = new javax.swing.JPanel();
        Gambar1 = new javax.swing.JLabel();
        Nama1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        Kolom2 = new javax.swing.JPanel();
        Gambar2 = new javax.swing.JLabel();
        Nama2 = new javax.swing.JLabel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jButton4 = new javax.swing.JButton();
        Kolom3 = new javax.swing.JPanel();
        Gambar3 = new javax.swing.JLabel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jButton5 = new javax.swing.JButton();
        Nama3 = new javax.swing.JLabel();
        Kolom4 = new javax.swing.JPanel();
        Gambar4 = new javax.swing.JLabel();
        pili4 = new javax.swing.JRadioButton();
        jButton6 = new javax.swing.JButton();
        Nama4 = new javax.swing.JLabel();
        Kolom5 = new javax.swing.JPanel();
        Gambar5 = new javax.swing.JLabel();
        Nama5 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        Kolom6 = new javax.swing.JPanel();
        Gambar6 = new javax.swing.JLabel();
        Nama6 = new javax.swing.JLabel();
        jRadioButton6 = new javax.swing.JRadioButton();
        jButton8 = new javax.swing.JButton();
        kolom7 = new javax.swing.JPanel();
        Gambar7 = new javax.swing.JLabel();
        Nama7 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        kolom8 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        kolom9 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        kolom10 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jRadioButton10 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Puki = new javax.swing.JComboBox<>();
        jButton14 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));

        jPanelkir1.setBackground(new java.awt.Color(153, 153, 153));

        jPanel6.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Data Pasien");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(118, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(94, 94, 94))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Barang");

        isi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isi1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Harga");

        jButton13.setText("Simpan");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelkir1Layout = new javax.swing.GroupLayout(jPanelkir1);
        jPanelkir1.setLayout(jPanelkir1Layout);
        jPanelkir1Layout.setHorizontalGroup(
            jPanelkir1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelkir1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelkir1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton13)
                    .addGroup(jPanelkir1Layout.createSequentialGroup()
                        .addGroup(jPanelkir1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelkir1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(isi2, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                            .addComponent(isi1))))
                .addContainerGap())
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelkir1Layout.setVerticalGroup(
            jPanelkir1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelkir1Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelkir1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(isi1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelkir1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(isi2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jButton13)
                .addGap(15, 15, 15))
        );

        jPanel7.setBackground(new java.awt.Color(204, 204, 204));
        jPanel7.setLayout(new java.awt.GridLayout(2, 0, 8, 8));

        Kolom1.setBackground(new java.awt.Color(204, 204, 204));
        Kolom1.setForeground(new java.awt.Color(153, 153, 255));

        Gambar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modul3/pkg3/gambar1.jpg"))); // NOI18N

        Nama1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Nama1.setForeground(new java.awt.Color(255, 255, 255));
        Nama1.setText("Paramex");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("Pilih");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(204, 204, 255));
        jButton1.setText("Detail");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Kolom1Layout = new javax.swing.GroupLayout(Kolom1);
        Kolom1.setLayout(Kolom1Layout);
        Kolom1Layout.setHorizontalGroup(
            Kolom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(Kolom1Layout.createSequentialGroup()
                .addGroup(Kolom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Gambar1)
                    .addGroup(Kolom1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(Nama1))
                    .addGroup(Kolom1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jRadioButton1)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        Kolom1Layout.setVerticalGroup(
            Kolom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Kolom1Layout.createSequentialGroup()
                .addComponent(Gambar1)
                .addGap(12, 12, 12)
                .addComponent(Nama1)
                .addGap(12, 12, 12)
                .addComponent(jRadioButton1)
                .addGap(12, 12, 12)
                .addComponent(jButton1))
        );

        jPanel7.add(Kolom1);

        Kolom2.setBackground(new java.awt.Color(204, 204, 204));
        Kolom2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Gambar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modul3/pkg3/gambal2.jpg"))); // NOI18N
        Kolom2.add(Gambar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 104, -1));

        Nama2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Nama2.setForeground(new java.awt.Color(255, 255, 255));
        Nama2.setText("Promag");
        Kolom2.add(Nama2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 106, -1, -1));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("Pilih");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        Kolom2.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 139, 75, -1));

        jButton4.setBackground(new java.awt.Color(204, 204, 255));
        jButton4.setText("Detail");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        Kolom2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 178, 104, -1));

        jPanel7.add(Kolom2);

        Kolom3.setBackground(new java.awt.Color(204, 204, 204));
        Kolom3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Gambar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modul3/pkg3/gambar3.jpg"))); // NOI18N
        Kolom3.add(Gambar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jRadioButton3.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton3.setText("Pilih");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        Kolom3.add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 139, -1, -1));

        jButton5.setBackground(new java.awt.Color(204, 204, 255));
        jButton5.setText("Detail");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        Kolom3.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 178, 106, -1));

        Nama3.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        Nama3.setForeground(new java.awt.Color(255, 255, 255));
        Nama3.setText("Antangin");
        Kolom3.add(Nama3, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 106, -1, -1));

        jPanel7.add(Kolom3);

        Kolom4.setBackground(new java.awt.Color(204, 204, 204));
        Kolom4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Gambar4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modul3/pkg3/gambar4.jpg"))); // NOI18N
        Kolom4.add(Gambar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        buttonGroup1.add(pili4);
        pili4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        pili4.setForeground(new java.awt.Color(255, 255, 255));
        pili4.setText("Pilih");
        pili4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pili4ActionPerformed(evt);
            }
        });
        pili4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pili4KeyReleased(evt);
            }
        });
        Kolom4.add(pili4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 139, 58, -1));

        jButton6.setBackground(new java.awt.Color(204, 204, 255));
        jButton6.setText("Detail");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        Kolom4.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 178, 100, -1));

        Nama4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Nama4.setForeground(new java.awt.Color(255, 255, 255));
        Nama4.setText("Konidin");
        Kolom4.add(Nama4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 106, -1, -1));

        jPanel7.add(Kolom4);

        Kolom5.setBackground(new java.awt.Color(204, 204, 204));
        Kolom5.setForeground(new java.awt.Color(204, 204, 204));
        Kolom5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Gambar5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modul3/pkg3/gambar5 (1).jpg"))); // NOI18N
        Kolom5.add(Gambar5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Nama5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Nama5.setForeground(new java.awt.Color(255, 255, 255));
        Nama5.setText(" Vitacimin");
        Kolom5.add(Nama5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 106, 84, -1));

        jButton7.setBackground(new java.awt.Color(204, 204, 255));
        jButton7.setText("Detail");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        Kolom5.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 178, 106, -1));

        buttonGroup1.add(jRadioButton5);
        jRadioButton5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jRadioButton5.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton5.setText("Pilih");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });
        Kolom5.add(jRadioButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 139, -1, -1));

        jPanel7.add(Kolom5);

        Kolom6.setBackground(new java.awt.Color(204, 204, 204));
        Kolom6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Gambar6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modul3/pkg3/gambar6.jpg"))); // NOI18N
        Kolom6.add(Gambar6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Nama6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Nama6.setForeground(new java.awt.Color(255, 255, 255));
        Nama6.setText("Vomitrol");
        Kolom6.add(Nama6, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 106, -1, -1));

        buttonGroup1.add(jRadioButton6);
        jRadioButton6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jRadioButton6.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton6.setText("Pilih");
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });
        Kolom6.add(jRadioButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jButton8.setBackground(new java.awt.Color(204, 204, 255));
        jButton8.setText("Detail");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        Kolom6.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 100, -1));

        jPanel7.add(Kolom6);

        kolom7.setBackground(new java.awt.Color(204, 204, 204));
        kolom7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Gambar7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modul3/pkg3/Gambar7.jpg"))); // NOI18N
        kolom7.add(Gambar7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Nama7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Nama7.setForeground(new java.awt.Color(255, 255, 255));
        Nama7.setText("Stofmag");
        kolom7.add(Nama7, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 106, -1, -1));

        jButton9.setBackground(new java.awt.Color(204, 204, 255));
        jButton9.setText("Detail");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        kolom7.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 100, -1));

        buttonGroup1.add(jRadioButton7);
        jRadioButton7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jRadioButton7.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton7.setText("Pilih");
        jRadioButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton7ActionPerformed(evt);
            }
        });
        kolom7.add(jRadioButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 60, -1));

        jPanel7.add(kolom7);

        kolom8.setBackground(new java.awt.Color(204, 204, 204));
        kolom8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modul3/pkg3/Gambar8.jpg"))); // NOI18N
        kolom8.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Paracetamol");
        kolom8.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 106, -1, -1));

        jButton10.setBackground(new java.awt.Color(204, 204, 255));
        jButton10.setText("Detail");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        kolom8.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 107, -1));

        buttonGroup1.add(jRadioButton8);
        jRadioButton8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jRadioButton8.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton8.setText("Pilih");
        jRadioButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton8ActionPerformed(evt);
            }
        });
        kolom8.add(jRadioButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jPanel7.add(kolom8);

        kolom9.setBackground(new java.awt.Color(204, 204, 204));
        kolom9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modul3/pkg3/Gambar9.jpg"))); // NOI18N
        jLabel15.setText("jLabel15");
        kolom9.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Komix");
        kolom9.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 106, -1, -1));

        jButton11.setBackground(new java.awt.Color(204, 204, 255));
        jButton11.setText("Detail");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        kolom9.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 107, -1));

        buttonGroup1.add(jRadioButton9);
        jRadioButton9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jRadioButton9.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton9.setText("Pilih");
        jRadioButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton9ActionPerformed(evt);
            }
        });
        kolom9.add(jRadioButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jPanel7.add(kolom9);

        kolom10.setBackground(new java.awt.Color(204, 204, 204));
        kolom10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modul3/pkg3/gambar10.jpg"))); // NOI18N
        kolom10.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jButton12.setBackground(new java.awt.Color(204, 204, 255));
        jButton12.setText("Detail");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        kolom10.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 104, -1));

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Super Tetra");
        kolom10.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 106, -1, -1));

        buttonGroup1.add(jRadioButton10);
        jRadioButton10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jRadioButton10.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton10.setText("Pilih");
        jRadioButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton10ActionPerformed(evt);
            }
        });
        kolom10.add(jRadioButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jPanel7.add(kolom10);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modul3/pkg3/Logo-Kimia-Farma (1).png"))); // NOI18N

        jPanel9.setBackground(new java.awt.Color(153, 153, 153));

        jPanel10.setBackground(new java.awt.Color(102, 102, 102));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Saran Obat");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap())
        );

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Gejala");

        Puki.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<<<<<<Piliham Gejala>>>> >", "Demam", "Asam Lambung", "Sakit Kepala", "Masuk Angin", "Meningkatkan daya tahan tubuh", "Sakit Perut", "Tenggorokan gatal", "Elergi", " ", " ", " ", " " }));

        jButton14.setText("OK");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Puki, 0, 228, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton14)))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Puki, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton14)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelkir1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jPanelkir1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modul3/pkg3/Logo-Kimia-Farma (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(270, 270, 270)
                .addComponent(jLabel5)
                .addContainerGap(319, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);

        jButton3.setText("Keluar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
        isi1.setText("Antangin");
        isi2.setText("2000");
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        isi1.setText("Paramex");
        isi2.setText("3000");
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new Dtail1().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        new Dtail2().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        new Dtail6().setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void isi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isi1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isi1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        new Dtail3().setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        new Dtail4().setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        new Dtail5().setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        new Dtail7().setVisible(true);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        new Dtail8().setVisible(true);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        String kolom = isi1.getText();
        String kalam = isi2.getText();
        
        System.out.println(kolom);
        if(kolom.isEmpty() ||kalam.isEmpty()){
            JOptionPane.showMessageDialog(this,"Silahkan isi data terlebi dahulu","PERINGATAN",JOptionPane.WARNING_MESSAGE);
            
        }else{
            JOptionPane.showMessageDialog(this,"Barang anda telah tersimpan","PERINGATAN",JOptionPane.INFORMATION_MESSAGE);
        }
        
        
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        new Dtail9().setVisible(true);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        new Dtail10().setVisible(true);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        int pilih = Puki.getSelectedIndex();
    
    if (pilih == 0){
        JOptionPane.showMessageDialog(this,"TOLONG PILIH GEJALA TERLEBIH DAHULU", "WARNING", JOptionPane.WARNING_MESSAGE);
    }else if (pilih == 1){
        JOptionPane.showMessageDialog(this,"Paracetamol", "REKOMENDASI OBAT", JOptionPane.INFORMATION_MESSAGE);
    }else if (pilih == 2){
        JOptionPane.showMessageDialog(this,"Promag", "REKOMENDASI OBAT", JOptionPane.INFORMATION_MESSAGE);
    }else if (pilih == 3){
        JOptionPane.showMessageDialog(this,"Paramex", "REKOMENDASI OBAT", JOptionPane.INFORMATION_MESSAGE);
    }else if (pilih == 4){
        JOptionPane.showMessageDialog(this,"Antangin", "REKOMENDASI OBAT", JOptionPane.INFORMATION_MESSAGE);
    }else if (pilih == 5){
        JOptionPane.showMessageDialog(this,"Vitacimin", "REKOMENDASI OBAT", JOptionPane.INFORMATION_MESSAGE);
    }else if (pilih == 6){
        JOptionPane.showMessageDialog(this,"Stopmag", "REKOMENDASI OBAT", JOptionPane.INFORMATION_MESSAGE);
    }else if (pilih == 7){
        JOptionPane.showMessageDialog(this,"Konidin", "REKOMENDASI OBAT", JOptionPane.INFORMATION_MESSAGE);
    }else if (pilih == 8){
        JOptionPane.showMessageDialog(this,"Komix", "REKOMENDASI OBAT", JOptionPane.INFORMATION_MESSAGE);
    }
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Puki.setSelectedItem("<<<<<<Piliham Gejala>>>> >");
        buttonGroup1.clearSelection();
        isi1.setText("");
        isi2.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void pili4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pili4ActionPerformed
        // TODO add your handling code here:
        isi1.setText("Konidin");
        isi2.setText("4000");
        
    }//GEN-LAST:event_pili4ActionPerformed

    private void pili4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pili4KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_pili4KeyReleased

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        isi1.setText("Promag");
        isi2.setText("24000");
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
        // TODO add your handling code here:
        isi1.setText("Vitacimin");
        isi2.setText("2000");
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
        // TODO add your handling code here:
        isi1.setText("Vomitrol");
        isi2.setText("200000");
    }//GEN-LAST:event_jRadioButton6ActionPerformed

    private void jRadioButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton7ActionPerformed
        // TODO add your handling code here:
        isi1.setText("Stofmag");
        isi2.setText("32000");
    }//GEN-LAST:event_jRadioButton7ActionPerformed

    private void jRadioButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton8ActionPerformed
        // TODO add your handling code here:
        isi1.setText("Paracetamol");
        isi2.setText("5000");
    }//GEN-LAST:event_jRadioButton8ActionPerformed

    private void jRadioButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton9ActionPerformed
        // TODO add your handling code here:
        isi1.setText("Komix");
        isi2.setText("3000");
    }//GEN-LAST:event_jRadioButton9ActionPerformed

    private void jRadioButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton10ActionPerformed
        // TODO add your handling code here:
        isi1.setText("Super Tetra");
        isi2.setText("20000");
    }//GEN-LAST:event_jRadioButton10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Desain1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Desain1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Desain1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Desain1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Desain1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Gambar1;
    private javax.swing.JLabel Gambar2;
    private javax.swing.JLabel Gambar3;
    private javax.swing.JLabel Gambar4;
    private javax.swing.JLabel Gambar5;
    private javax.swing.JLabel Gambar6;
    private javax.swing.JLabel Gambar7;
    private javax.swing.JPanel Kolom1;
    private javax.swing.JPanel Kolom2;
    private javax.swing.JPanel Kolom3;
    private javax.swing.JPanel Kolom4;
    private javax.swing.JPanel Kolom5;
    private javax.swing.JPanel Kolom6;
    private javax.swing.JLabel Nama1;
    private javax.swing.JLabel Nama2;
    private javax.swing.JLabel Nama3;
    private javax.swing.JLabel Nama4;
    private javax.swing.JLabel Nama5;
    private javax.swing.JLabel Nama6;
    private javax.swing.JLabel Nama7;
    private javax.swing.JComboBox<String> Puki;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField isi1;
    private javax.swing.JTextField isi2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelkir1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JPanel kolom10;
    private javax.swing.JPanel kolom7;
    private javax.swing.JPanel kolom8;
    private javax.swing.JPanel kolom9;
    private javax.swing.JRadioButton pili4;
    // End of variables declaration//GEN-END:variables
}
