/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package modul3;

import javax.swing.JOptionPane;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author Muhammad Fajri
 */
public class Soal1 extends javax.swing.JFrame {
    Icon satu = new javax.swing.ImageIcon(getClass().getResource("/modul3/1.png"));
    Icon dua = new javax.swing.ImageIcon(getClass().getResource("/modul3/2.png"));
    Icon tiga = new javax.swing.ImageIcon(getClass().getResource("/modul3/3.png"));
    Icon empat = new javax.swing.ImageIcon(getClass().getResource("/modul3/4.png"));
    Icon lima = new javax.swing.ImageIcon(getClass().getResource("/modul3/5.png"));
    Icon enam = new javax.swing.ImageIcon(getClass().getResource("/modul3/6.png"));
    Icon tujuh = new javax.swing.ImageIcon(getClass().getResource("/modul3/7.png"));
    Icon delapan = new javax.swing.ImageIcon(getClass().getResource("/modul3/8.png"));
    Icon sembilan = new javax.swing.ImageIcon(getClass().getResource("/modul3/9.png"));
    Icon sepuluh = new javax.swing.ImageIcon(getClass().getResource("/modul3/10.png"));
    Icon sebelas = new javax.swing.ImageIcon(getClass().getResource("/modul3/11.png"));
    Icon duabelas = new javax.swing.ImageIcon(getClass().getResource("/modul3/12.png"));
    Icon tigabelas = new javax.swing.ImageIcon(getClass().getResource("/modul3/13.png"));
    Icon empatbelas = new javax.swing.ImageIcon(getClass().getResource("/modul3/14.png"));
    Icon limabelas = new javax.swing.ImageIcon(getClass().getResource("/modul3/15.png"));
    Icon enambelas = new javax.swing.ImageIcon(getClass().getResource("/modul3/16.png"));
    Icon tujuhbelas = new javax.swing.ImageIcon(getClass().getResource("/modul3/17.png"));
    Icon delapanbelas = new javax.swing.ImageIcon(getClass().getResource("/modul3/18.png"));

    /**
     * Creates new form Soal1
     */
    public Soal1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        BG = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Obat1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        Saranobat = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Gejala = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        Hargaobat = new javax.swing.JTextField();
        Jenisobat = new javax.swing.JTextField();
        Catatan = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modul3/Banner.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        BG.setBackground(new java.awt.Color(0, 204, 204));
        BG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modul3/atas.png"))); // NOI18N
        jPanel1.add(jLabel1, new java.awt.GridBagConstraints());

        BG.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 840, 100));

        Obat1.setBackground(new java.awt.Color(0, 204, 204));
        Obat1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Obat1.setLayout(new java.awt.GridLayout(3, 0, 2, 2));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modul3/1.png"))); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        Obat1.add(jButton1);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modul3/2.png"))); // NOI18N
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        Obat1.add(jButton5);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modul3/3.png"))); // NOI18N
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });
        Obat1.add(jButton7);

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modul3/4.png"))); // NOI18N
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });
        Obat1.add(jButton9);

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modul3/5.png"))); // NOI18N
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton11MouseClicked(evt);
            }
        });
        Obat1.add(jButton11);

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modul3/6.png"))); // NOI18N
        jButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton12MouseClicked(evt);
            }
        });
        Obat1.add(jButton12);

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modul3/7.png"))); // NOI18N
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });
        Obat1.add(jButton8);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modul3/8.png"))); // NOI18N
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        Obat1.add(jButton6);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modul3/9.png"))); // NOI18N
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        Obat1.add(jButton2);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modul3/10.png"))); // NOI18N
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        Obat1.add(jButton4);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modul3/11.png"))); // NOI18N
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        Obat1.add(jButton3);

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modul3/12.png"))); // NOI18N
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton10MouseClicked(evt);
            }
        });
        Obat1.add(jButton10);

        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modul3/13.png"))); // NOI18N
        jButton13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton13MouseClicked(evt);
            }
        });
        Obat1.add(jButton13);

        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modul3/14.png"))); // NOI18N
        jButton14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton14MouseClicked(evt);
            }
        });
        Obat1.add(jButton14);

        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modul3/15.png"))); // NOI18N
        jButton15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton15MouseClicked(evt);
            }
        });
        Obat1.add(jButton15);

        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modul3/16.png"))); // NOI18N
        jButton16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton16MouseClicked(evt);
            }
        });
        Obat1.add(jButton16);

        jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modul3/17.png"))); // NOI18N
        jButton17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton17MouseClicked(evt);
            }
        });
        Obat1.add(jButton17);

        jButton18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modul3/18.png"))); // NOI18N
        jButton18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton18MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton18MouseEntered(evt);
            }
        });
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        Obat1.add(jButton18);

        BG.add(Obat1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 610, 230));

        jLabel5.setFont(new java.awt.Font("Sirukota", 1, 24)); // NOI18N
        jLabel5.setText("DAFtar obat  yang tersedia");
        BG.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, -1, -1));

        jLabel6.setFont(new java.awt.Font("Sirukota", 1, 24)); // NOI18N
        jLabel6.setText("PERIKSA GEJALA dan solusi obat");
        BG.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, -1, 30));

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        jPanel6.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Sirukota", 1, 14)); // NOI18N
        jLabel7.setText("Pilih gejala anda");
        jPanel6.add(jLabel7);
        jLabel7.setBounds(20, 20, 150, 15);
        jPanel6.add(Saranobat);
        Saranobat.setBounds(130, 50, 210, 30);

        jLabel8.setFont(new java.awt.Font("Sirukota", 1, 14)); // NOI18N
        jLabel8.setText("Saran Obat");
        jPanel6.add(jLabel8);
        jLabel8.setBounds(20, 50, 100, 15);

        jLabel9.setFont(new java.awt.Font("Sirukota", 1, 18)); // NOI18N
        jLabel9.setText("Harga obat");
        jPanel6.add(jLabel9);
        jLabel9.setBounds(20, 90, 100, 19);

        jLabel10.setFont(new java.awt.Font("Sirukota", 1, 18)); // NOI18N
        jLabel10.setText("Jenis Obat");
        jPanel6.add(jLabel10);
        jLabel10.setBounds(20, 130, 90, 19);

        Gejala.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Gejala yang kamu alami", "Pusing", "Nyeri Otot", "Demam", "Sakit Kepala", "Diare", "Mual dan Mabuk Perjalanan", "Infeksi Jamur", "Sakit Perut dan Gangguan Lambung", "Flu dan Demam Ringan", "Nyeri Haid", "Gatal-gatal atau Alergi" }));
        Gejala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GejalaActionPerformed(evt);
            }
        });
        jPanel6.add(Gejala);
        Gejala.setBounds(130, 10, 210, 30);

        jLabel11.setFont(new java.awt.Font("Sirukota", 1, 18)); // NOI18N
        jLabel11.setText("Catatan");
        jPanel6.add(jLabel11);
        jLabel11.setBounds(20, 170, 80, 19);
        jPanel6.add(Hargaobat);
        Hargaobat.setBounds(130, 90, 210, 30);
        jPanel6.add(Jenisobat);
        Jenisobat.setBounds(130, 130, 210, 30);
        jPanel6.add(Catatan);
        Catatan.setBounds(130, 170, 210, 30);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modul3/Rumah sakit telang indah.png"))); // NOI18N
        jLabel12.setText("jLabel12");
        jPanel6.add(jLabel12);
        jLabel12.setBounds(350, 10, 250, 160);

        jLabel13.setFont(new java.awt.Font("Sirukota", 1, 18)); // NOI18N
        jLabel13.setText("Semoga Cepat Sembuh");
        jPanel6.add(jLabel13);
        jLabel13.setBounds(380, 180, 190, 19);

        BG.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 420, 610, 210));

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));
        jPanel2.setLayout(new java.awt.GridLayout(1, 1));

        jLabel2.setBackground(new java.awt.Color(0, 204, 204));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modul3/Kanan.png"))); // NOI18N
        jPanel2.add(jLabel2);

        BG.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, 550));

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));
        jPanel3.setLayout(new java.awt.GridLayout(1, 1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modul3/Kiri.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel3.add(jLabel3);

        BG.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 100, 90, 540));

        jPanel5.setBackground(new java.awt.Color(0, 204, 204));
        jPanel5.setLayout(new java.awt.GridBagLayout());

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modul3/bawah.png"))); // NOI18N
        jPanel5.add(jLabel14, new java.awt.GridBagConstraints());

        BG.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 650, 830, 100));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BG, javax.swing.GroupLayout.PREFERRED_SIZE, 829, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
         JOptionPane.showMessageDialog(this, 
    "Nama Obat: Promax\n"
    + "Fungsi: Sakit mag, ganguan lambung,\n"
    + "Harga: Rp 4.000 (per box 12 tablet)", 
    "INFORMASI OBAT", 
    JOptionPane.INFORMATION_MESSAGE, satu);


    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
         JOptionPane.showMessageDialog(this, 
    "Nama Obat: Tolak Angin\n"
    + "Fungsi: Meredahkan masuk angin, mual, perut kembung\n"
    + "Harga: Rp 15.000 (per box 12 saset)", 
    "INFORMASI OBAT", 
    JOptionPane.INFORMATION_MESSAGE, dua);
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        // TODO add your handling code here:
         JOptionPane.showMessageDialog(this, 
    "Nama Obat: Mixagrip\n"
    + "Fungsi: Meredahkan flu, demam, sakit kepala, dan nyeri tubuh\n"
    + "Harga: Rp 3.000 (per box 4 tablet)", 
    "INFORMASI OBAT", 
    JOptionPane.INFORMATION_MESSAGE, tiga);
    }//GEN-LAST:event_jButton7MouseClicked

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
        // TODO add your handling code here:
         JOptionPane.showMessageDialog(this, 
    "Nama Obat: Bodrex\n"
    + "Fungsi: sakit kepala, demam ,gejala flu ringan\n"
    + "Harga: Rp 4.000 (per box 4 tablet)", 
    "INFORMASI OBAT", 
    JOptionPane.INFORMATION_MESSAGE, empat);
    }//GEN-LAST:event_jButton9MouseClicked

    private void jButton11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseClicked
        // TODO add your handling code here:
         JOptionPane.showMessageDialog(this, 
    "Nama Obat: Antimo\n"
    + "Fungsi: Mengatasi mabuk perjalana\n"
    + "Harga: Rp 3.000 (per box 12 tablet)", 
    "INFORMASI OBAT", 
    JOptionPane.INFORMATION_MESSAGE, lima);
    }//GEN-LAST:event_jButton11MouseClicked

    private void jButton12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton12MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, 
    "Nama Obat: Antihistamin\n"
    + "Fungsi: Alergi gatal-gatal, ruam,bersin, dan mata berair\n"
    + "Harga: Rp 20.000 (per box 10 tablet)", 
    "INFORMASI OBAT", 
    JOptionPane.INFORMATION_MESSAGE, enam);
    }//GEN-LAST:event_jButton12MouseClicked

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, 
    "Nama Obat: Paramex\n"
    + "Fungsi: Meredakan sakit kepala, nyeri otot, dan demam ringan\n"
    + "Harga: Rp 10.000 (per box 10 tablet)", 
    "INFORMASI OBAT", 
    JOptionPane.INFORMATION_MESSAGE, tujuh);
    }//GEN-LAST:event_jButton8MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, 
    "Nama Obat: Salonpas\n"
    + "Fungsi: Meredakan nyeri otot, sakit kepala, dan nyeri sendi "
    + "ringan dengan cara dioleskan pada area yang sakit\n"
    + "Harga: Rp 20.000 (per box dengan 5 patch)", 
    "INFORMASI OBAT", 
    JOptionPane.INFORMATION_MESSAGE, delapan);
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, 
    "Nama Obat: Paracetamol\n"
    + "Fungsi: Meredakan nyeri ringan hingga sedang dan menurunkan demam\n"
    + "Harga: Rp 5.000 (per strip 10 tablet)", 
    "INFORMASI OBAT", 
    JOptionPane.INFORMATION_MESSAGE, sembilan);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, 
    "Nama Obat: Autan\n"
    + "Fungsi: Repelan untuk mengusir nyamuk dan serangga lainnya\n"
    + "Harga: Rp 25.000 (per botol 100 ml)", 
    "INFORMASI OBAT", 
    JOptionPane.INFORMATION_MESSAGE, sepuluh);
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, 
    "Nama Obat: Antasida\n"
    + "Fungsi: Meredakan gangguan lambung seperti asam lambung, "
    + "nyeri ulu hati, dan perut kembung\n"
    + "Harga: Rp 15.000 (per box dengan 10 tablet)", 
    "INFORMASI OBAT", 
    JOptionPane.INFORMATION_MESSAGE, sebelas);
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, 
    "Nama Obat: Ibuprofen\n"
    + "Fungsi: Meredakan nyeri ringan hingga sedang, seperti sakit kepala,"
    + " sakit gigi, dan nyeri otot\n"
    + "Harga: Rp 10.000 (per strip 10 tablet)", 
    "INFORMASI OBAT", 
    JOptionPane.INFORMATION_MESSAGE, duabelas);
    }//GEN-LAST:event_jButton10MouseClicked

    private void jButton13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton13MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, 
    "Nama Obat: Listerine\n"
    + "Fungsi: Pembilas mulut untuk membantu mengurangi plak, bau mulut, "
    + "dan menjaga kesehatan gigi dan gusi\n"
    + "Harga: Rp 35.000 (per botol 250 ml)", 
    "INFORMASI OBAT", 
    JOptionPane.INFORMATION_MESSAGE, tigabelas);
    }//GEN-LAST:event_jButton13MouseClicked

    private void jButton14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton14MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, 
    "Nama Obat: Canesten\n"
    + "Fungsi: Obat untuk mengatasi infeksi jamur pada kulit, kaki atlet, "
    + "dan infeksi vagina\n"
    + "Harga: Rp 50.000 (per tube 20 g)", 
    "INFORMASI OBAT", 
    JOptionPane.INFORMATION_MESSAGE, empatbelas);
    }//GEN-LAST:event_jButton14MouseClicked

    private void jButton15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton15MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, 
    "Nama Obat: Imodium\n"
    + "Fungsi: Mengatasi diare dengan cara memperlambat gerakan usus\n"
    + "Harga: Rp 15.000 (per strip 10 kapsul)", 
    "INFORMASI OBAT", 
    JOptionPane.INFORMATION_MESSAGE, limabelas);
    }//GEN-LAST:event_jButton15MouseClicked

    private void jButton16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton16MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, 
    "Nama Obat: Amoxicillin\n"
    + "Fungsi: Antibiotik untuk mengobati infeksi bakteri seperti "
    + "infeksi saluran pernapasan, telinga, dan saluran kemih\n"
    + "Harga: Rp 20.000 (per strip 10 kapsul)", 
    "INFORMASI OBAT", 
    JOptionPane.INFORMATION_MESSAGE, enambelas);
    }//GEN-LAST:event_jButton16MouseClicked

    private void jButton17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton17MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, 
    "Nama Obat: Mefinal\n"
    + "Fungsi: Obat pereda nyeri dan antiinflamasi untuk mengatasi"
    + " nyeri haid, nyeri otot, dan nyeri lainnya\n"
    + "Harga: Rp 25.000 (per strip 10 tablet)", 
    "INFORMASI OBAT", 
    JOptionPane.INFORMATION_MESSAGE, tujuhbelas);
    }//GEN-LAST:event_jButton17MouseClicked

    private void jButton18MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton18MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton18MouseEntered

    private void jButton18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton18MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, 
    "Nama Obat: Panadol\n"
    + "Fungsi: Meredakan nyeri ringan hingga sedang, seperti sakit kepala, sakit gigi, dan demam\n"
    + "Harga: Rp 10.000 (per strip 10 tablet)", 
    "INFORMASI OBAT", 
    JOptionPane.INFORMATION_MESSAGE, delapanbelas);
    }//GEN-LAST:event_jButton18MouseClicked

    private void GejalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GejalaActionPerformed
        // TODO add your handling code here:
        String Pilihobat = Gejala.getSelectedItem().toString();
        

        if(Pilihobat.equals("Pilih Gejala yang kamu alami")){
            Saranobat.setText("");
            Hargaobat.setText("");
            Jenisobat.setText("");
            Catatan.setText("");
            
        } else if(Pilihobat.equals("Pusing")){
            Saranobat.setText("Panadol");
            Hargaobat.setText("Rp. 10.000");
            Jenisobat.setText("Tablet");
            Catatan.setText("Meredakan pusing");
            ImageIcon icon = new ImageIcon("src/modul3/Panadol.png");
            jLabel12.setIcon(icon);
            

        } else if(Pilihobat.equals("Nyeri Otot")){
            Saranobat.setText("Salonpas");
            Hargaobat.setText("Rp. 20.000");
            Jenisobat.setText("Patch");
            Catatan.setText("Meredakan nyeri otot dan sendi");
            ImageIcon icon = new ImageIcon("src/modul3/Salonpas.png");
            jLabel12.setIcon(icon);

        } else if(Pilihobat.equals("Demam")){
            Saranobat.setText("Paracetamol");
            Hargaobat.setText("Rp. 5.000");
            Jenisobat.setText("Tablet");
            Catatan.setText("Menurunkan demam dan meredakan nyeri ringan");
            ImageIcon icon = new ImageIcon("src/modul3/Paracetamol.png");
            jLabel12.setIcon(icon);

        } else if(Pilihobat.equals("Sakit Kepala")){
            Saranobat.setText("Bodrex");
            Hargaobat.setText("Rp. 7.000");
            Jenisobat.setText("Tablet");
            Catatan.setText("Meredakan sakit kepala");
            ImageIcon icon = new ImageIcon("src/modul3/Bodrex.png");
            jLabel12.setIcon(icon);

        } else if(Pilihobat.equals("Mual dan Mabuk Perjalanan")){
            Saranobat.setText("Antimo");
            Hargaobat.setText("Rp. 10.000");
            Jenisobat.setText("Tablet");
            Catatan.setText("Mengatasi mual dan mabuk perjalanan");
            ImageIcon icon = new ImageIcon("src/modul3/Antimo.png");
            jLabel12.setIcon(icon);

        } else if(Pilihobat.equals("Infeksi Jamur")){
            Saranobat.setText("Canesten");
            Hargaobat.setText("Rp. 50.000");
            Jenisobat.setText("Krim");
            Catatan.setText("Mengatasi infeksi jamur pada kulit");
            ImageIcon icon = new ImageIcon("src/modul3/Canesten.png");
            jLabel12.setIcon(icon);

        } else if(Pilihobat.equals("Sakit Perut dan Gangguan Lambung")){
            Saranobat.setText("Antasida");
            Hargaobat.setText("Rp. 15.000");
            Jenisobat.setText("Tablet");
            Catatan.setText("Meredakan gangguan lambung dan asam lambung");
            ImageIcon icon = new ImageIcon("src/modul3/AntasidaDoen.png");
            jLabel12.setIcon(icon);

        } else if(Pilihobat.equals("Flu dan Demam Ringan")){
            Saranobat.setText("Mixagrip");
            Hargaobat.setText("Rp. 20.000");
            Jenisobat.setText("Tablet");
            Catatan.setText("Meredakan gejala flu seperti demam, sakit kepala, "
            + "dan hidung tersumbat");
            ImageIcon icon = new ImageIcon("src/modul3/Mixagrip.png");
            jLabel12.setIcon(icon);

        } else if(Pilihobat.equals("Nyeri Haid")){
            Saranobat.setText("Mefinal");
            Hargaobat.setText("Rp. 25.000");
            Jenisobat.setText("Tablet");
            Catatan.setText("Mengatasi nyeri haid dan nyeri lainnya");
            ImageIcon icon = new ImageIcon("src/modul3/Mefinal.png");
            jLabel12.setIcon(icon);

        } else if(Pilihobat.equals("Gatal-gatal atau Alergi")){
            Saranobat.setText("Antihistamine");
            Hargaobat.setText("Rp. 12.000");
            Jenisobat.setText("Tablet");
            Catatan.setText("Meredakan gejala alergi gatal");
            ImageIcon icon = new ImageIcon("src/modul3/Antihistamine.png");
            jLabel12.setIcon(icon);
        }

    }//GEN-LAST:event_GejalaActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton18ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Soal1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Soal1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Soal1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Soal1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Soal1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BG;
    private javax.swing.JTextField Catatan;
    private javax.swing.JComboBox<String> Gejala;
    private javax.swing.JTextField Hargaobat;
    private javax.swing.JTextField Jenisobat;
    private javax.swing.JPanel Obat1;
    private javax.swing.JTextField Saranobat;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    // End of variables declaration//GEN-END:variables
}
