/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package modul3;

import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Muhammad Fajri
 */
public class Soal2 extends javax.swing.JFrame {
    
    /**
     * Creates new form Cobasoal2
     */
    public Soal2() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        javax.swing.ButtonGroup GrupBulan = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jCheckBox11 = new javax.swing.JCheckBox();
        jCheckBox12 = new javax.swing.JCheckBox();
        HitungBayar = new javax.swing.JButton();
        Reset = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        BelumBayar = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        Riwayat = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        TotalPembayaran = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        StatusPembayaran = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Kembalian = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Nama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Nim = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Spp = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        Uang = new javax.swing.JTextField();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        java.awt.GridBagLayout jPanel1Layout = new java.awt.GridBagLayout();
        jPanel1Layout.columnWidths = new int[] {0, 5, 0, 5, 0};
        jPanel1Layout.rowHeights = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0};
        jPanel1.setLayout(jPanel1Layout);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Bulan Yang Dibayar:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        jPanel1.add(jLabel5, gridBagConstraints);

        jCheckBox1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jCheckBox1.setText("Januari");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jCheckBox1, gridBagConstraints);

        jCheckBox2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jCheckBox2.setText("Februari");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jCheckBox2, gridBagConstraints);

        jCheckBox3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jCheckBox3.setText("Maret");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jCheckBox3, gridBagConstraints);

        jCheckBox4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jCheckBox4.setText("April");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jCheckBox4, gridBagConstraints);

        jCheckBox5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jCheckBox5.setText("Mei");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jCheckBox5, gridBagConstraints);

        jCheckBox6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jCheckBox6.setText("Juni");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jCheckBox6, gridBagConstraints);

        jCheckBox7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jCheckBox7.setText("Juli");
        jCheckBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox7ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jCheckBox7, gridBagConstraints);

        jCheckBox8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jCheckBox8.setText("Agustus");
        jCheckBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox8ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jCheckBox8, gridBagConstraints);

        jCheckBox9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jCheckBox9.setText("September");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jCheckBox9, gridBagConstraints);

        jCheckBox10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jCheckBox10.setText("Oktober");
        jCheckBox10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox10ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jCheckBox10, gridBagConstraints);

        jCheckBox11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jCheckBox11.setText("November");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jCheckBox11, gridBagConstraints);

        jCheckBox12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jCheckBox12.setText("Desember");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jCheckBox12, gridBagConstraints);

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 310, 170));

        HitungBayar.setBackground(new java.awt.Color(51, 255, 0));
        HitungBayar.setText("Hitung Pembayaran");
        HitungBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HitungBayarActionPerformed(evt);
            }
        });
        jPanel2.add(HitungBayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 610, 310, 33));

        Reset.setBackground(new java.awt.Color(255, 0, 0));
        Reset.setText("Reset");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });
        jPanel2.add(Reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 660, 310, 34));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Bulan Yang Belum Dibayar:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 320, 190, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Riwayat Pembayaran:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 500, 170, -1));

        BelumBayar.setEditable(false);
        BelumBayar.setBackground(new java.awt.Color(255, 204, 204));
        BelumBayar.setColumns(20);
        BelumBayar.setRows(5);
        jScrollPane3.setViewportView(BelumBayar);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 340, 420, 160));

        Riwayat.setBackground(new java.awt.Color(255, 204, 204));
        Riwayat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Riwayat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama", "Nim", "Bulan", "HargaSpp", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Riwayat.setVerifyInputWhenFocusTarget(false);
        jScrollPane1.setViewportView(Riwayat);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 530, 420, 150));

        jPanel3.setBackground(new java.awt.Color(255, 204, 204));
        jPanel3.setLayout(new java.awt.GridLayout(6, 1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Total Pembayaran:");
        jPanel3.add(jLabel9);

        TotalPembayaran.setEditable(false);
        TotalPembayaran.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.add(TotalPembayaran);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Status Pembayaran:");
        jPanel3.add(jLabel10);

        StatusPembayaran.setEditable(false);
        StatusPembayaran.setBackground(new java.awt.Color(255, 255, 255));
        StatusPembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StatusPembayaranActionPerformed(evt);
            }
        });
        jPanel3.add(StatusPembayaran);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Uang Kembalian:");
        jPanel3.add(jLabel1);

        Kembalian.setEditable(false);
        Kembalian.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.add(Kembalian);

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 420, 180));

        jPanel4.setBackground(new java.awt.Color(255, 204, 204));
        jPanel4.setLayout(new java.awt.GridLayout(6, 1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Nama Mahasiswa:");
        jPanel4.add(jLabel2);

        Nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamaActionPerformed(evt);
            }
        });
        jPanel4.add(Nama);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("NIM Mahasiswa:");
        jPanel4.add(jLabel3);
        jPanel4.add(Nim);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("SPP Yang Harus dibayar:");
        jPanel4.add(jLabel4);
        jPanel4.add(Spp);

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 310, 190));

        jPanel5.setBackground(new java.awt.Color(255, 204, 204));
        jPanel5.setLayout(new java.awt.GridLayout(2, 1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Masukan Uang Anda:");
        jPanel5.add(jLabel6);

        Uang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                UangKeyReleased(evt);
            }
        });
        jPanel5.add(Uang);

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 310, 70));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modul3/BG.png"))); // NOI18N
        jPanel2.add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 750));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 831, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox7ActionPerformed

    private void jCheckBox10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox10ActionPerformed

    private void NamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_NamaActionPerformed

    private void HitungBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HitungBayarActionPerformed
        // TODO add your handling code here:
        int totalPembayaranSebelumnya = 0;
        int hargaSPP;
        
    
        if(Nama.getText().isEmpty()){
        JOptionPane.showMessageDialog(this, "Lengkapi data nama terlebih dahulu",
                "Peringatan", JOptionPane.WARNING_MESSAGE);
        return;
        }
        if(Nim.getText().isEmpty()){
        JOptionPane.showMessageDialog(this, "Lengkapi data Nim terlebih dahulu", 
                "Peringatan", JOptionPane.WARNING_MESSAGE);
        return;
        }
        
        try {
        hargaSPP = Integer.parseInt(Spp.getText());
        } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Masukkan harga SPP yang valid!", "Error", JOptionPane.ERROR_MESSAGE);
        return;
        }
        
        if (jCheckBox1.isSelected() && jCheckBox2.isSelected() 
            && jCheckBox3.isSelected() && jCheckBox4.isSelected()
            && jCheckBox5.isSelected() && jCheckBox6.isSelected() 
            && jCheckBox7.isSelected() && jCheckBox8.isSelected()
            && jCheckBox9.isSelected() && jCheckBox10.isSelected() 
            && jCheckBox11.isSelected() && jCheckBox12.isSelected()) {
        
            StatusPembayaran.setText("Lunas");
        } else {
            StatusPembayaran.setText("Menunggak");
        }
        

    StringBuilder bulanBelumBayar = new StringBuilder();
    StringBuilder bulanDibayar = new StringBuilder();

    int jumlahBulanDipilih = 0;
    
    if (jCheckBox1.isSelected()) {
        jumlahBulanDipilih++;
        jCheckBox1.setEnabled(false);  
        bulanDibayar.append("Januari\n"); 
    } else {
        bulanBelumBayar.append("Januari\n");
    }
    
    if (jCheckBox2.isSelected()) {
        jumlahBulanDipilih++;
        jCheckBox2.setEnabled(false);  
        bulanDibayar.append("Februari\n"); 
    } else {
        bulanBelumBayar.append("Februari\n");
    }
    
    if (jCheckBox3.isSelected()) {
        jumlahBulanDipilih++;
        jCheckBox3.setEnabled(false); 
        bulanDibayar.append("Maret\n"); 
    } else {
        bulanBelumBayar.append("Maret\n");
    }
    
    if (jCheckBox4.isSelected()) {
        jumlahBulanDipilih++;
        jCheckBox4.setEnabled(false);  
        bulanDibayar.append("April\n");  
    } else {
        bulanBelumBayar.append("April\n");
    }
    
    if (jCheckBox5.isSelected()) {
        jumlahBulanDipilih++;
        jCheckBox5.setEnabled(false); 
        bulanDibayar.append("Mei\n"); 
    } else {
        bulanBelumBayar.append("Mei\n");
    }
    
    if (jCheckBox6.isSelected()) {
        jumlahBulanDipilih++;
        jCheckBox6.setEnabled(false); 
        bulanDibayar.append("Juni\n"); 
    } else {
        bulanBelumBayar.append("Juni\n");
    }
    
    if (jCheckBox7.isSelected()) {
        jumlahBulanDipilih++;
        jCheckBox7.setEnabled(false);  
        bulanDibayar.append("Juli\n"); 
    } else {
        bulanBelumBayar.append("Juli\n");
    }
    
    if (jCheckBox8.isSelected()) {
        jumlahBulanDipilih++;
        jCheckBox8.setEnabled(false);  
        bulanDibayar.append("Agustus\n"); 
    } else {
        bulanBelumBayar.append("Agustus\n");
    }
    
    if (jCheckBox9.isSelected()) {
        jumlahBulanDipilih++;
        jCheckBox9.setEnabled(false); 
        bulanDibayar.append("September\n");  
    } else {
        bulanBelumBayar.append("September\n");
    }
    
    if (jCheckBox10.isSelected()) {
        jumlahBulanDipilih++;
        jCheckBox10.setEnabled(false);  
        bulanDibayar.append("Oktober\n"); 
    } else {
        bulanBelumBayar.append("Oktober\n");
    }
    
    if (jCheckBox11.isSelected()) {
        jumlahBulanDipilih++;
        jCheckBox11.setEnabled(false); 
        bulanDibayar.append("November\n");  
    } else {
        bulanBelumBayar.append("November\n");
    }
    
    if (jCheckBox12.isSelected()) {
        jumlahBulanDipilih++;
        jCheckBox12.setEnabled(false); 
        bulanDibayar.append("Desember\n");  
    } else {
        bulanBelumBayar.append("Desember\n");
    }
    
        BelumBayar.setText(bulanBelumBayar.toString());
   
        int totalBayarBaru = jumlahBulanDipilih * hargaSPP;
        int totalBayar = totalPembayaranSebelumnya + totalBayarBaru;
        totalPembayaranSebelumnya = totalBayar;

        
        TotalPembayaran.setText(Integer.toString(totalBayar));
        
        
       
                                         
           DefaultTableModel iniTable = (DefaultTableModel) Riwayat.getModel();
           Object[] rowData = new Object[12];

           String nama = Nama.getText();
           rowData[0] = nama;
           String nim = Nim.getText();
           rowData[1] = nim;
           
           
            StringBuilder selectedBulan = new StringBuilder();
            if(jCheckBox1.isSelected()){
                selectedBulan.append(jCheckBox1.getText()).append(", ");
            }
            if(jCheckBox2.isSelected()){
                selectedBulan.append(jCheckBox2.getText()).append(", ");
            }
            if(jCheckBox3.isSelected()){
                selectedBulan.append(jCheckBox3.getText()).append(", ");
            }
            if(jCheckBox4.isSelected()){
                selectedBulan.append(jCheckBox4.getText()).append(", ");
            }
            if(jCheckBox5.isSelected()){
                selectedBulan.append(jCheckBox5.getText()).append(", ");
            }
            if(jCheckBox6.isSelected()){
                selectedBulan.append(jCheckBox6.getText()).append(", ");
            }
            if(jCheckBox7.isSelected()){
                selectedBulan.append(jCheckBox7.getText()).append(", ");
            }
            if(jCheckBox8.isSelected()){
                selectedBulan.append(jCheckBox8.getText()).append(", ");
            }
            if(jCheckBox9.isSelected()){
                selectedBulan.append(jCheckBox9.getText()).append(", ");
            }
            if(jCheckBox10.isSelected()){
                selectedBulan.append(jCheckBox10.getText()).append(", ");
            }
            if(jCheckBox11.isSelected()){
                selectedBulan.append(jCheckBox11.getText()).append(", ");
            }
            if(jCheckBox12.isSelected()){
                selectedBulan.append(jCheckBox12.getText()).append(", ");
            }
            
            if (selectedBulan.length() > 0) {
                selectedBulan.setLength(selectedBulan.length() - 2);
            }

            rowData[2] = selectedBulan.toString();

           
           String spp = Spp.getText();
           rowData[3] = spp;
           
           String status = ("Lunas");
           rowData[4] = status;

           iniTable.addRow(rowData);
           
        
    }//GEN-LAST:event_HitungBayarActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        // TODO add your handling code here:
        Nama.setText(null);
        Nim.setText(null);
        Spp.setText(null);
        TotalPembayaran.setText(null);
        StatusPembayaran.setText(null);
        BelumBayar.setText(null);
        Kembalian.setText(null);
        Uang.setText(null);
        TotalPembayaran.setText("");
        
        DefaultTableModel model = (DefaultTableModel) Riwayat.getModel();
        model.setRowCount(0);
        
        // Aktifkan kembali semua checkbox
        jCheckBox1.setEnabled(true);
        jCheckBox2.setEnabled(true);
        jCheckBox3.setEnabled(true);
        jCheckBox4.setEnabled(true);
        jCheckBox5.setEnabled(true);
        jCheckBox6.setEnabled(true);
        jCheckBox7.setEnabled(true);
        jCheckBox8.setEnabled(true);
        jCheckBox9.setEnabled(true);
        jCheckBox10.setEnabled(true);
        jCheckBox11.setEnabled(true);
        jCheckBox12.setEnabled(true);

        // Reset semua checkbox menjadi tidak terpilih
        jCheckBox1.setSelected(false);
        jCheckBox2.setSelected(false);
        jCheckBox3.setSelected(false);
        jCheckBox4.setSelected(false);
        jCheckBox5.setSelected(false);
        jCheckBox6.setSelected(false);
        jCheckBox7.setSelected(false);
        jCheckBox8.setSelected(false);
        jCheckBox9.setSelected(false);
        jCheckBox10.setSelected(false);
        jCheckBox11.setSelected(false);
        jCheckBox12.setSelected(false);

        
    
    
    }//GEN-LAST:event_ResetActionPerformed

    private void jCheckBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox8ActionPerformed

    private void StatusPembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StatusPembayaranActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_StatusPembayaranActionPerformed

    private void UangKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UangKeyReleased
        // TODO add your handling code here:
        try{
            int Harga_total = Integer.parseInt(Spp.getText());
            int cash = Integer.parseInt(Uang.getText());
       
        if (cash < Harga_total){
            Kembalian.setText("Uang anda kurang");
        } else {
            int kembalian = cash - Harga_total;
            Kembalian.setText(String.valueOf(kembalian));        
        }    
        } catch (NumberFormatException e) {
            Kembalian.setText("Masukkan angka saja");
        } 
    }//GEN-LAST:event_UangKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Soal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Soal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Soal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Soal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Soal2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JTextArea BelumBayar;
    private javax.swing.JButton HitungBayar;
    private javax.swing.JTextField Kembalian;
    private javax.swing.JTextField Nama;
    private javax.swing.JTextField Nim;
    private javax.swing.JButton Reset;
    private javax.swing.JTable Riwayat;
    private javax.swing.JTextField Spp;
    private javax.swing.JTextField StatusPembayaran;
    private javax.swing.JTextField TotalPembayaran;
    private javax.swing.JTextField Uang;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
