/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package modul4;
import java.util.Random;
import javax.swing.Icon;
import javax.swing.JOptionPane;
import javax.swing.ImageIcon;

/**
 *
 * @author Muhammad Fajri
 */
public class Soal1 extends javax.swing.JFrame {
    Icon Kalah = new javax.swing.ImageIcon(getClass().getResource("/modul4/kalah.png"));
    Icon Menang = new javax.swing.ImageIcon(getClass().getResource("/modul4/Menang.png"));
    Icon Lose = new javax.swing.ImageIcon(getClass().getResource("/modul4/lose.png"));
    Icon Angka = new javax.swing.ImageIcon(getClass().getResource("/modul4/angka.png"));
    
    int kesempatan = 10;
    String[][] data_score = new String[10][2];;
    int index = 0;
    StringBuilder score_border = new StringBuilder();
    int maxrandom = 100;
    Random angka1 = new Random();
    int tebakan = angka1.nextInt(maxrandom+1);
    
    
    public Soal1() {
        initComponents();  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        shadowRenderer1 = new raven.tabbed.ShadowRenderer();
        tabbedPaneCustom1 = new raven.tabbed.TabbedPaneCustom();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Tebak = new javax.swing.JTextField();
        Hasil = new javax.swing.JTextField();
        Score = new javax.swing.JTextField();
        TebakAngka = new javax.swing.JButton();
        Reset = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        highscore = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Sirukota", 1, 18)); // NOI18N
        jLabel2.setText("TEBAK Angka");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(170, 190, 100, 19);

        jLabel3.setFont(new java.awt.Font("Sirukota", 1, 18)); // NOI18N
        jLabel3.setText("Periksa Jawaban");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(170, 250, 140, 19);

        jLabel4.setFont(new java.awt.Font("Sirukota", 1, 18)); // NOI18N
        jLabel4.setText("SCORE Anda");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(170, 300, 100, 19);

        Tebak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TebakActionPerformed(evt);
            }
        });
        jPanel3.add(Tebak);
        Tebak.setBounds(320, 190, 350, 30);

        Hasil.setEditable(false);
        Hasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HasilActionPerformed(evt);
            }
        });
        jPanel3.add(Hasil);
        Hasil.setBounds(320, 240, 350, 30);

        Score.setEditable(false);
        Score.setText("0");
        Score.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ScoreActionPerformed(evt);
            }
        });
        jPanel3.add(Score);
        Score.setBounds(320, 290, 350, 30);

        TebakAngka.setBackground(new java.awt.Color(102, 255, 102));
        TebakAngka.setText("TEBAK(10)");
        TebakAngka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TebakAngkaActionPerformed(evt);
            }
        });
        jPanel3.add(TebakAngka);
        TebakAngka.setBounds(320, 340, 140, 30);

        Reset.setBackground(new java.awt.Color(255, 0, 0));
        Reset.setText("RESET");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });
        jPanel3.add(Reset);
        Reset.setBounds(540, 340, 130, 30);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modul4/1.png"))); // NOI18N
        jPanel3.add(jLabel6);
        jLabel6.setBounds(0, -10, 940, 590);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 939, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        tabbedPaneCustom1.addTab("Permainan", jPanel1);

        jPanel4.setBackground(new java.awt.Color(255, 204, 255));
        jPanel4.setLayout(null);

        jButton1.setText("RESET");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1);
        jButton1.setBounds(266, 708, 142, 23);

        highscore.setEditable(false);
        highscore.setColumns(20);
        highscore.setRows(5);
        jScrollPane2.setViewportView(highscore);

        jPanel4.add(jScrollPane2);
        jScrollPane2.setBounds(220, 90, 530, 420);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modul4/3.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel4.add(jLabel1);
        jLabel1.setBounds(0, -20, 940, 630);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        tabbedPaneCustom1.addTab("PapanScore", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPaneCustom1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabbedPaneCustom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        // TODO add your handling code here:
        Tebak.setText(null);
        Hasil.setText(null);
        Score.setText("0");
        TebakAngka.setText("Tebak(10)");
        highscore.setText(null);
    }//GEN-LAST:event_ResetActionPerformed

    private void TebakAngkaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TebakAngkaActionPerformed
        // TODO add your handling code here:
        try {
            int angka2 = Integer.parseInt(Tebak.getText());
            if (tebakan < angka2) {
                kesempatan -= 1;
                TebakAngka.setText("Tebak (" + kesempatan + ")");
                Hasil.setText("Angka Tebakan Lebih Kecil");
                Tebak.setText("");
                Score.setText("0");
                JOptionPane.showMessageDialog(this, "TEBAKAN ANDA SALAH", "PESAN PEMBERITAHUAN", JOptionPane.INFORMATION_MESSAGE,Kalah);
                if (kesempatan == 0) {
                    kesempatan = 10;
                    TebakAngka.setText("Tebak (" + kesempatan + ")");
                    JOptionPane.showMessageDialog(this, "KESEMPATAN ANDA HABIS \n" + "ANDA GAGAL", "PESAN PERINGATAN", JOptionPane.INFORMATION_MESSAGE, Lose);
                    Tebak.setText("");
                    Hasil.setText("");
                    Score.setText("0");
                    TebakAngka.setText("Tebak(10)");
                }
            } else if (tebakan > angka2) {
                Hasil.setText("Angka Tebakan Lebih Besar");
                kesempatan -= 1;
                TebakAngka.setText("Tebak (" + kesempatan + ")");
                Tebak.setText("");
                Score.setText("0");
                JOptionPane.showMessageDialog(this, "TEBAKAN ANDA SALAH", "PESAN PEMBERITAHUAN", JOptionPane.INFORMATION_MESSAGE,Kalah);
                if (kesempatan == 0) {
                    kesempatan = 10;
                    TebakAngka.setText("Tebak (" + kesempatan + ")");
                    JOptionPane.showMessageDialog(this, "KESEMPATAN ANDA HABIS \n" + "ANDA GAGAL", "PESAN PERINGATAN", JOptionPane.ERROR_MESSAGE, Lose);
                    Tebak.setText("");
                    Hasil.setText("");
                    Score.setText("0");
                    TebakAngka.setText("Tebak(10)");
                }
            } else if (tebakan == angka2) {
                Hasil.setText(String.valueOf(tebakan));
                int hasil = kesempatan * 10; // Menghitung skor berdasarkan kesempatan
                Score.setText(String.valueOf(hasil));
                JOptionPane.showMessageDialog(this, "SELAMAT TEBAKAN ANDA BENAR", "INFORMASI", JOptionPane.INFORMATION_MESSAGE,Menang);
                Tebak.setText("");
                Hasil.setText("");
                Score.setText("0");
                TebakAngka.setText("Tebak(10)");
                kesempatan = 10;

                // Mengambil input nama dari pemain
                String nama;
                    do {
                        nama = JOptionPane.showInputDialog(this, "SILAHKAN MASUKAN NAMA", "Nama player", JOptionPane.INFORMATION_MESSAGE);

                        if (nama == null) {
                            JOptionPane.showMessageDialog(this, "Nama tidak boleh kosong! Silahkan masukkan nama.", "Peringatan", JOptionPane.WARNING_MESSAGE);
                        } else if (nama.trim().isEmpty()) {
                            JOptionPane.showMessageDialog(this, "Nama tidak boleh kosong atau hanya spasi! Silahkan masukkan nama.", "Peringatan", JOptionPane.WARNING_MESSAGE);
                        }
                    } while (nama == null || nama.trim().isEmpty());

                    if (index < data_score.length) {
                        data_score[index][0] = nama;
                        data_score[index][1] = String.valueOf(hasil);
                        index++;
                    }

                    Tebak.setText("");
                    Hasil.setText("");
                    Score.setText("0");
                    TebakAngka.setText("Tebak(10)");

                    score_border.setLength(0);

                    for (int i = 0; i < index; i++) {
                        score_border.append("Name: ").append(data_score[i][0]).append(", Score: ").append(data_score[i][1]).append("\n");
                    }
                    highscore.setText(score_border.toString());
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "TEBAKAN HARUS BERUPA ANGKA", "PESAN PERINGATAN", JOptionPane.ERROR_MESSAGE,Angka);
        }
    }//GEN-LAST:event_TebakAngkaActionPerformed

    private void ScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ScoreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ScoreActionPerformed

    private void HasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HasilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HasilActionPerformed

    private void TebakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TebakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TebakActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Soal1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Soal1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Soal1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Soal1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Soal1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Hasil;
    private javax.swing.JButton Reset;
    private javax.swing.JTextField Score;
    private javax.swing.JTextField Tebak;
    private javax.swing.JButton TebakAngka;
    private javax.swing.JTextArea highscore;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private raven.tabbed.ShadowRenderer shadowRenderer1;
    private raven.tabbed.TabbedPaneCustom tabbedPaneCustom1;
    // End of variables declaration//GEN-END:variables
}
