
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author DAVID IMAN FURQONI
 */
public class SPPfix extends javax.swing.JFrame {

    /**
     * Creates new form SPPfix
     */
    public SPPfix() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        container = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        sejutaSetengah = new javax.swing.JRadioButton();
        sejuta = new javax.swing.JRadioButton();
        limaRatus = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pembayaran = new javax.swing.JTable();
        body = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        januari = new javax.swing.JCheckBox();
        februari = new javax.swing.JCheckBox();
        maret = new javax.swing.JCheckBox();
        april = new javax.swing.JCheckBox();
        mei = new javax.swing.JCheckBox();
        juni = new javax.swing.JCheckBox();
        juli = new javax.swing.JCheckBox();
        agustus = new javax.swing.JCheckBox();
        september = new javax.swing.JCheckBox();
        oktober = new javax.swing.JCheckBox();
        november = new javax.swing.JCheckBox();
        desember = new javax.swing.JCheckBox();
        kirim = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        container.setLayout(new java.awt.BorderLayout());

        header.setBackground(new java.awt.Color(51, 51, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("BAYAR UANG SPP ANDA SEKARANG !!!");
        header.add(jLabel1);

        container.add(header, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel2.setText("Nama");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel3.setText("Jumlah SPP Tiap Bulan");

        buttonGroup1.add(sejutaSetengah);
        sejutaSetengah.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        sejutaSetengah.setText("1.500.000");

        buttonGroup1.add(sejuta);
        sejuta.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        sejuta.setText("1.000.000");

        buttonGroup1.add(limaRatus);
        limaRatus.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        limaRatus.setText("500.000");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sejutaSetengah)
                    .addComponent(sejuta)
                    .addComponent(limaRatus))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(sejutaSetengah)
                .addGap(18, 18, 18)
                .addComponent(sejuta)
                .addGap(18, 18, 18)
                .addComponent(limaRatus)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        container.add(jPanel1, java.awt.BorderLayout.LINE_START);

        jPanel3.setBackground(new java.awt.Color(51, 51, 255));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        pembayaran.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama", "Nominal", "Bulan Bayar"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        pembayaran.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(pembayaran);
        if (pembayaran.getColumnModel().getColumnCount() > 0) {
            pembayaran.getColumnModel().getColumn(0).setResizable(false);
            pembayaran.getColumnModel().getColumn(1).setResizable(false);
            pembayaran.getColumnModel().getColumn(2).setResizable(false);
            pembayaran.getColumnModel().getColumn(2).setPreferredWidth(450);
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 977, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                .addContainerGap())
        );

        container.add(jPanel3, java.awt.BorderLayout.PAGE_END);

        body.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        body.setLayout(new java.awt.GridBagLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel4.setText("pilih bulan yang akan dibayar");
        body.add(jLabel4, new java.awt.GridBagConstraints());

        januari.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        januari.setText("Januari");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 34;
        gridBagConstraints.ipady = 26;
        body.add(januari, gridBagConstraints);

        februari.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        februari.setText("Februari");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 26;
        gridBagConstraints.ipady = 26;
        body.add(februari, gridBagConstraints);

        maret.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        maret.setText("Maret");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 39;
        gridBagConstraints.ipady = 28;
        body.add(maret, gridBagConstraints);

        april.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        april.setText("April");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 44;
        gridBagConstraints.ipady = 28;
        body.add(april, gridBagConstraints);

        mei.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        mei.setText("Mei");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 29;
        body.add(mei, gridBagConstraints);

        juni.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        juni.setText("Juni");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 49;
        gridBagConstraints.ipady = 31;
        body.add(juni, gridBagConstraints);

        juli.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        juli.setText("Juli");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 43;
        body.add(juli, gridBagConstraints);

        agustus.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        agustus.setText("Agustus");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 16;
        body.add(agustus, gridBagConstraints);

        september.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        september.setText("September");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        body.add(september, gridBagConstraints);

        oktober.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        oktober.setText("Oktober");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 14;
        body.add(oktober, gridBagConstraints);

        november.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        november.setText("November");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 1;
        body.add(november, gridBagConstraints);

        desember.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        desember.setText("Desember");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 1;
        body.add(desember, gridBagConstraints);

        kirim.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        kirim.setText("Kirim");
        kirim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kirimActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 12;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 7);
        body.add(kirim, gridBagConstraints);

        container.add(body, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kirimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kirimActionPerformed
        // TODO add your handling code here:
        if (nama.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Isi Nama Terlebih Dahulu!", "Pemberitahuan!", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        if (!januari.isSelected() && !februari.isSelected() && !maret.isSelected() && !april.isSelected() && !mei.isSelected() && !juni.isSelected() && !juli.isSelected() && !agustus.isSelected() && !september.isSelected() && !oktober.isSelected() && !november.isSelected() && !desember.isSelected()) {
            JOptionPane.showMessageDialog(null, "Anda harus memilih minimal satu bulan untuk pembayaran SPP.", "Pemberitahuan", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
       
        
        try{
            DefaultTableModel model = (DefaultTableModel) pembayaran.getModel();
            
            String Nama = nama.getText();
            String bulanBayar = "";
            int totalBulan = 0;
            int PerBulan;
            
            if (limaRatus.isSelected()) {
            PerBulan = 500000;
        } else if (sejuta.isSelected()) {
            PerBulan = 1000000;
        } else if (sejutaSetengah.isSelected()) {
            PerBulan = 1500000;
        }else {
            JOptionPane.showMessageDialog(null, "Pilih salah satu nominal SPP per bulan.", "Pemberitahuan", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
            
            if (januari.isSelected()) {
                bulanBayar += "Januari, ";
                totalBulan++;
            }
            if (februari.isSelected()) {
                bulanBayar += "Februari, ";
                totalBulan++;
            }
            if (maret.isSelected()) {
                bulanBayar += "Maret, ";
                totalBulan++;
            }
            if (april.isSelected()) {
                bulanBayar += "April, ";
                totalBulan++;
            }
            if (mei.isSelected()) {
                bulanBayar += "Mei, ";
                totalBulan++;
            }
            if (juni.isSelected()) {
                bulanBayar += "Juni, ";
                totalBulan++;
            }
            if (juli.isSelected()) {
                bulanBayar += "Juli, ";
                totalBulan++;
            }
            if (agustus.isSelected()) {
                bulanBayar += "Agustus, ";
                totalBulan++;
            }
            if (september.isSelected()) {
                bulanBayar += "September, ";
                totalBulan++;
            }
            if (oktober.isSelected()) {
                bulanBayar += "Oktober, ";
                totalBulan++;
            }
            if (november.isSelected()) {
                bulanBayar += "November, ";
                totalBulan++;
            }
            if (desember.isSelected()) {
                bulanBayar += "Desember, ";
                totalBulan++;
            }
            
            bulanBayar = bulanBayar.trim().endsWith(",") ? bulanBayar.substring(0, bulanBayar.length() - 2) : bulanBayar;
        int totalSPP = PerBulan * totalBulan;
        
        Object[] rowData = new Object[4];
        rowData[0] = Nama;
        rowData[1] = totalSPP;
        rowData[2] = bulanBayar;

        model.addRow(rowData);
        resetForm();
        JOptionPane.showMessageDialog(null, "Data Sukses ditambahkan", "Sukses", JOptionPane.INFORMATION_MESSAGE);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Format SPP tidak valid. Masukkan angka.", "Error", JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_kirimActionPerformed

    private void resetForm() {
        nama.setText("");
        buttonGroup1.clearSelection();
        januari.setSelected(false);
        februari.setSelected(false);
        maret.setSelected(false);
        april.setSelected(false);
        mei.setSelected(false);
        juni.setSelected(false);
        juli.setSelected(false);
        agustus.setSelected(false);
        september.setSelected(false);
        oktober.setSelected(false);
        november.setSelected(false);
        desember.setSelected(false);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SPPfix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SPPfix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SPPfix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SPPfix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SPPfix().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox agustus;
    private javax.swing.JCheckBox april;
    private javax.swing.JPanel body;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel container;
    private javax.swing.JCheckBox desember;
    private javax.swing.JCheckBox februari;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox januari;
    private javax.swing.JCheckBox juli;
    private javax.swing.JCheckBox juni;
    private javax.swing.JButton kirim;
    private javax.swing.JRadioButton limaRatus;
    private javax.swing.JCheckBox maret;
    private javax.swing.JCheckBox mei;
    private javax.swing.JTextField nama;
    private javax.swing.JCheckBox november;
    private javax.swing.JCheckBox oktober;
    private javax.swing.JTable pembayaran;
    private javax.swing.JRadioButton sejuta;
    private javax.swing.JRadioButton sejutaSetengah;
    private javax.swing.JCheckBox september;
    // End of variables declaration//GEN-END:variables
}
